### ISSUE TITLE
Updating Unified Runtime Specifiction documentation

### ISSUE THREAD

**Issue by igchor** [oneapi-src/unified-runtime#102]
I noticed that https://spec.oneapi.io/unified-runtime/latest/index.html is quite outdated. Do we plan to have some automation to publish updated spec on that webpage?

Do we know where that website is hosted?

**Comment by kbenzie** [comment]
I don't actually know how that works, perhaps @zackwaters might be able to point us in the right direction?

As for automation, yes I have been thinking about using GitHub Pages to view the rendered HTML for each PR. Once we know more about how to update https://spec.oneapi.io/unified-runtime/latest/index.html then we can also automate those updates.

**Comment by igchor** [comment]
I believe this is solved already
