### ISSUE TITLE
Add `urPluginGetOpaqueData`

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#103]
# Issue
PI has a [piextPluginGetOpaqueData](https://github.com/intel/llvm/blob/c4932957929f94afe7f87bee009eea5e2b5cd6bf/sycl/include/sycl/detail/pi.h#L1792) entry point that is used in the DPC++ runtime [here](https://github.com/intel/llvm/blob/f4fc927095949ed9403b049662ec60923d56b067/sycl/source/detail/pi.cpp#L68).

# Task
Add an equivalent `urGetOpaqueData` entry point to Unified Runtime.

**Comment by veselypeta** [comment]
It appears that this extension is useful for Intel's ESIMD architectures. I see it being used within the `esimd_emulator`.
I assume the plugin for ESIMD is closed source?
[link] to the relevant extension

**Comment by kbenzie** [comment]
No-one has talked the porting the ESIMD plugin in the WG. Its not on any of the architecture diagrams that have been discussed. That might well point to this not introducing this entrypoint to UR until we are certain its required.
