### ISSUE TITLE
Consider aligning type of UR_KERNEL_INFO_NUM_ARGS with CL

### ISSUE THREAD

**Issue by aarongreig** [oneapi-src/unified-runtime#1038]
UR's `UR_KERNEL_INFO_NUM_ARGS` query is `size_t` according to the spec, but this is a little strange given its closest equivalent [CL_KERNEL_NUM_ARGS](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_KERNEL_NUM_ARGS) is cl_uint. If we were to align with CL on this the CL implementation would be a little bit nicer for being able to skip the cast, and anything further up the stack that might expect us to align with CL would no longer potentially be surprised.

**Comment by aarongreig** [comment]
we should definitely do this, sycl's equivalent is also uint32_t https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_kernel_information_descriptors which is causing problems in e2e tests if we properly validate sizes in our GetInfo queries

**Comment by kbenzie** [comment]
agreed, it an unnecessary mismatch.

**Comment by aarongreig** [comment]
changes to address this now in https://github.com/oneapi-src/unified-runtime/pull/1212

**Comment by aarongreig** [comment]
the PR to do this got merged
