### ISSUE TITLE
CTS tests failing on multi-device scenarios

### ISSUE THREAD

**Issue by jandres742** [oneapi-src/unified-runtime#1063]
When running a CTS in a multi-device system, I see errors like:

```sh
[ FATAL ]/unified-runtime/build/_deps/googletest-src/googletest/include/gtest/internal/gtest-param-util.h:586::
Condition test_param_names.count(param_name) == 0 failed.
Duplicate parameterized test name 'Intel_R__oneAPI_Unified_Runtime_over_Level_Zero___Intel_R__Data_Center_GPU_Max_1550_', in /unified-runtime/test/conformance/context/urContextCreate.cpp line 10
```

the problem seem to be here

https://github.com/oneapi-src/unified-runtime/blob/adapters/test/conformance/testing/include/uur/fixtures.h#L97
```cpp
::testing::ValuesIn(uur::DevicesEnvironment::instance->devices),       \
```

where the name for tests are created for a set of devices, so if we have multiple devices with the same name, then test aborts.

WA at least for L0- for now is to use ZE_AFFINITY_MASK=0 to select only the first device.

@kbenzie , @pbalcer : are we aware of this? is there a way of fixing it w/o requiring the use of the affinity mask, or in the future, of the ONEAPI_DEVICE_SELECTOR?

**Comment by kbenzie** [comment]
This does remind me of a recent PR, to append the device index to the test name but I'm struggling to find where that was being discussed...

**Comment by kbenzie** [comment]
This has probably already been resolved in another PR, will need to check that.

**Comment by pbalcer** [comment]
Yes, https://github.com/oneapi-src/unified-runtime/pull/1805, we added multi-device PVC testing some time ago and were forced to fix it :)

**Comment by kbenzie** [comment]
Thanks, closing since its already fixed.
