### ISSUE TITLE
`urPlatformCreateWithNativeHandle` should accept adapter

### ISSUE THREAD

**Issue by alexbatashev** [oneapi-src/unified-runtime#1068]
Currently `urPlatformCreateWithNativeHandle` tries to extract dispatch table from native platform handle. That, however, can't work because the native handle may be anything, including nullptr, which may be a valid case for some adapters. So, instead the API should be something like:

```
UR_APIEXPORT ur_result_t UR_APICALL urPlatformCreateWithNativeHandle(ur_native_handle_t hNativePlatform, ur_adapter_handle_t adapter, const ur_platform_native_properties_t *pProperties, ur_platform_handle_t *phPlatform)
```

Which would be consistent with how SYCL handles the matter:
```
namespace sycl {

template <backend Backend>
platform make_platform(const backend_input_t<Backend, platform>& backendObject);

}
```
where backend is part of the API call.

This also reveals a big gap in CTS testing - CTS gets native object from the UR API and then feeds it back, which means that the creation of UR objects from external handles (e.g., from cuBLAS or something) is never tested.

**Comment by alexbatashev** [comment]
Other APIs seem to be OK, as they accept mostly accept a context (or something else in rare cases), and we can use that to extract ddi table. The PR with making this change is here: https://github.com/oneapi-src/unified-runtime/pull/1067

**Comment by alycm** [comment]
Thank you for the PR fixing the immediate issue.  Yes, it seems like we should also improve both the specification and CTS here.

**Comment by aarongreig** [comment]
this will be fixed by https://github.com/oneapi-src/unified-runtime/pull/1692
