### ISSUE TITLE
A possible extra word or typo in the INTRO

### ISSUE THREAD

**Issue by yingcong-wu** [oneapi-src/unified-runtime#1073]
Hi, in here
https://github.com/oneapi-src/unified-runtime/blob/a1fbbde74204905b52c626a166dd1944182fe096/scripts/core/INTRO.rst?plain=1#L69C47-L69C47

"the driver nor device provide may provide", is the fisrt "provide" an extra one or maybe like a "provider"?

**Comment by kbenzie** [comment]
Thanks, you're right. This statement is a little off and needs fixed.
