### ISSUE TITLE
Add `ur_memory_order_capabilities` bitfield 

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#109]
# Issue

PI has a [`pi_memory_order_capabilities`](https://github.com/intel/llvm/blob/c4932957929f94afe7f87bee009eea5e2b5cd6bf/sycl/include/sycl/detail/pi.h#L524) bit field used in the [DPC++ runtime](https://github.com/intel/llvm/blob/7b47ebb68d87f760785dd4a409fa4ea24b8235c4/sycl/source/detail/device_info.hpp#L264). The bitfield has the following values defined for it:
* `PI_MEMORY_ORDER_RELAXED`
* `PI_MEMORY_ORDER_ACQUIRE`
* `PI_MEMORY_ORDER_RELEASE`
* `PI_MEMORY_ORDER_ACQ_REL`
* `PI_MEMORY_ORDER_SEQ_CST`
This bitfield and its values are missing from UR.

# Task

Add a `ur_memory_order_capabilities` bitfield to UR to meet the requirements of the DPC++ runtime.

**Comment by FranklandJack** [comment]
* `PI_MEMORY_ORDER_RELAXED`
* `PI_MEMORY_ORDER_ACQUIRE`
* `PI_MEMORY_ORDER_RELEASE`
* `PI_MEMORY_ORDER_ACQ_REL`

Are only used in the CUDA adapter and `PI_MEMORY_ORDER_SEQ_CST` isn't used in any adapter, so there is a discussion to be had here of whether these values should be in UR or if they can be defined in the DPC++ headers instead.

**Comment by callumfare** [comment]
Since the last comment on this issue, the HIP adapter has also started using the `pi_memory_order_capabilities` bitfield. All adapters will need to implement this to support the matching SYCL device query, so this should be added to UR
