### ISSUE TITLE
Clang is not used in Windows builds in Github Actions workflow

### ISSUE THREAD

**Issue by PatKamin** [oneapi-src/unified-runtime#1111]
The compiler array for Windows build in the main Github Actions workflow file `cmake.yml` doesn't work as intended. Setting the compiler to `clang-cl.exe` results in building project with the `cl.exe` compiler, see example workflow run [log](https://github.com/oneapi-src/unified-runtime/actions/runs/6946918417/job/18899530429#step:5:22).

**Comment by kbenzie** [comment]
```
Run cmake -BD:\a\unified-runtime\unified-runtime/build -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe -DCMAKE_POLICY_DEFAULT_CMP0094=NEW -DUR_ENABLE_TRACING=ON -DUR_DEVELOPER_MODE=ON -DUR_BUILD_TESTS=ON -DUR_FORMAT_CPP_STYLE=ON 
CMake Warning:
  Ignoring extra path from command line:

   ".exe"
```

Is this a quoting issue?

**Comment by PatKamin** [comment]
No, it's not related to this issue. The one that you quoted comes from the ".exe" suffix which is redundant here, I think. See the example log line I've provided that the configured compiler is `cl.exe` instead of expected `clang-cl.exe`

**Comment by kbenzie** [comment]
When #1113 being merged, can this be closed?

**Comment by PatKamin** [comment]
> When #1113 being merged, can this be closed?

Yes, I'm closing this issue.
