### ISSUE TITLE
Add `PI_FP_SOFT_FLOAT`

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#113]
# Issue

PI defines the [`pi_device_fp_config`](https://github.com/intel/llvm/blob/c4932957929f94afe7f87bee009eea5e2b5cd6bf/sycl/include/sycl/detail/pi.h#L650) bitfield and the `PI_FP_SOFT_FLOAT` value for it which is used [here](https://github.com/intel/llvm/blob/7b47ebb68d87f760785dd4a409fa4ea24b8235c4/sycl/source/detail/device_info.hpp#L45) in the DPC++ runtime. UR defines the [`ur_fp_capability_flag_t`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3062) enumeration but doesn't have a `UR_FP_SOFT_FLOAT` entry.

# Task

Add a `UR_FP_SOFT_FLOAT` entry to the `ur_fp_capability_flag_t` enumeration so that UR meets the requirements to implement the DPC++ runtime.

**Comment by FranklandJack** [comment]
Again, this is another enumeration value that doesn't seem to be handled in any in tree adapter, so it may not actually be required as part of the DPC++ runtime implementation.

**Comment by kbenzie** [comment]
This comes from the SYCL spec `fp_config::soft_float` in section [A.3. Device information descriptors](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#appendix.device.descriptors) so UR should include this.
