### ISSUE TITLE
Change to CMake options to build all adapters

### ISSUE THREAD

**Issue by martygrant** [oneapi-src/unified-runtime#1132]
I introduced a PR https://github.com/oneapi-src/unified-runtime/pull/1126 which suggests a change to the CMake building flags so all adapters can be built using one flag, instead of specifying all of them. 

### Option 1
The PR linked above suggests a new flag `UR_BUILD_ADAPTER_ALL` which simply sets all other flags e.g. `UR_BUILD_ADAPTER_OPENCL` to `ON`.

### Option 2
One single flag with multiple options for different adapters. This would look like:
```
option(UR_BUILD_ADAPTER "build specific or all currently supported adapters (CUDA, OPENCL, HIP, L0, NATIVE_CPU or ALL)" OFF)
```
and example usage would be:
```
-DUR_BUILD_ADAPTER="CUDA" # builds only CUDA
-DUR_BUILD_ADAPTER="OPENCL;L0" # builds only OPENCL and L0
-DUR_BUILD_ADAPTER="ALL" # builds all supported adapters
```
Some logic for checking flags would need to change from:
```
if(UR_BUILD_ADAPTER_OPENCL)
    add_subdirectory(opencl)
endif()
```
to:
```
# convert the string option to a list
string(REPLACE ";" ";" ADAPTER_LIST "${UR_BUILD_ADAPTER}")
list(GET ADAPTER_LIST 0 FIRST_VALUE)

...

if ("OPENCL" IN_LIST ADAPTER_LIST OR "ALL" IN_LIST ADAPTER_LIST)
    add_subdirectory(opencl)
endif()
```

Additionally @jandres742 mentioned the text `Fetch and use all supported adapter from SYCL` in the README file is outdated and should be updated to reflect the current configuration in that it is DPC++ that fetches the adapter from the UR repo.

**Comment by lukaszstolarczuk** [comment]
I, personally, like option no. 1 (introduced in #1126). It's not intrusive and easy to maintain, it's just a wrapper to existing solution - requires no changes in existing scripts/workflows/etc.

As for the description of that option, I'd just write `Build all currently supported adapters.`

**Comment by jandres742** [comment]
+1 also on option 1.

**Comment by martygrant** [comment]
Could that be achieved by just changing it to `set(UR_BUILD_ADAPTER_L0 ON CACHE BOOL)`?
```
if (UR_BUILD_ADAPTER_ALL)
    set(UR_BUILD_ADAPTER_L0 ON CACHE BOOL)
    ...
endif()
```

**Comment by kbenzie** [comment]
That's still possible to get into weird states unless you use the `FORCE` flag but then you're overriding user set variables. I think the least surprising (hence most user friendly) method is to do checks like `if(UR_BUILD_ADAPTER_L0 OR UR_BUILD_ADAPTER_ALL)` instead of overriding the values of the individual adapter options.

**Comment by martygrant** [comment]
Yeah I updated the PR #1126 with the simpler option of adding the new flag to the pre-existing checks, cheers :)
