### ISSUE TITLE
Consider adding PROGRAM_INFO_IL

### ISSUE THREAD

**Issue by aarongreig** [oneapi-src/unified-runtime#1138]
Right now to query out the makings of a given program we have PROGRAM_INFO_SOURCE. Cuda and hip interpret this query as meaning "whatever pre-device-binary material you have for the program" and they return their stored binary - that could be a number of things (ptx, fat ELF binary, etc.) of which none are a source language. OpenCL and level zero interpret it literally: level zero will hit an error if you request program source as it doesn't consume anything that could be considered a source language, OpenCL translates it directly into the CL equivalent which behaves as you would expect.

If we added a PROGRAM_INFO_IL query all the adapters would be able to reliably return something sensible for it, and the CL adapter would still retain the ability to return a program's source code in the unlikely scenario that it's been given ownership of a native program handle that actually was created from source. Otherwise we should just rename PROGRAM_INFO_SOURCE to _IL so it can be useful for all adapters and unambiguous.

**Comment by kbenzie** [comment]
We don't support creating programs from source like OpenCL does with OpenCL C strings so `PROGRAM_INFO_SOURCE` is meaningless. `PROGRAM_INFO_IL` makes sense instead since we can either accept and intermediate langauge or program binaries.
