### ISSUE TITLE
Add Missing `ur_device_affinity_domain_flag_t` Enumerations

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#115]
# Issue

PI defines the [`pi_device_affinity_domain`](https://github.com/intel/llvm/blob/c4932957929f94afe7f87bee009eea5e2b5cd6bf/sycl/include/sycl/detail/pi.h#L635) bitfield which can take the following values:
* `PI_DEVICE_AFFINITY_DOMAIN_L4_CACHE`
* `PI_DEVICE_AFFINITY_DOMAIN_L3_CACHE`
* `PI_DEVICE_AFFINITY_DOMAIN_L2_CACHE`
* `PI_DEVICE_AFFINITY_DOMAIN_L1_CACHE`

which are used [here](https://github.com/intel/llvm/blob/7b47ebb68d87f760785dd4a409fa4ea24b8235c4/sycl/source/detail/device_info.hpp#L63), [here](https://github.com/intel/llvm/blob/7b47ebb68d87f760785dd4a409fa4ea24b8235c4/sycl/source/detail/device_info.hpp#L435), [here](https://github.com/intel/llvm/blob/7b47ebb68d87f760785dd4a409fa4ea24b8235c4/sycl/source/detail/device_info.hpp#L434) and [here](https://github.com/intel/llvm/blob/7b47ebb68d87f760785dd4a409fa4ea24b8235c4/sycl/source/detail/device_info.hpp#L433) respectively in the DPC++ runtime.

Unified Runtime defines the [`ur_device_affinity_domain_flag_t`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3109) enumeration but it is missing the above values.

# Task

Add the missing enumerations from above to Unified Runtime so that it meets the requirements of the DPC++ runtime.

**Comment by FranklandJack** [comment]
There is a bit of a question of whether the DPC++ runtime actually needs to use these enumerations, see the comments on https://github.com/oneapi-src/unified-runtime/pull/132.

**Comment by veselypeta** [comment]
These enums are likely not required for UR.

**Comment by kbenzie** [comment]
> These enums are likely not required for UR.

I don't think I agree, they are required for the [SYCL 2020 spec](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:device-class), see table 23.
