### ISSUE TITLE
Consider adding UR_PLATFORM_INFO_ADAPTER to ur_platform_info_t

### ISSUE THREAD

**Issue by fabiomestre** [oneapi-src/unified-runtime#1157]
`UR_PLATFORM_INFO_ADAPTER` would be a new enum in  `ur_platform_info_t` that returns the adapter handle for the given platform.

Reasoning:

When using the UR loader, `urAdapterGet()` can return more than 1 adapter. `urPlatformGet` then takes a list of adapters and returns all the supported platforms by those adapters. However, when using this workflow, it's not possible to know which adapter implements a given platform returned by `urPlatformGet()`. This is relevant because `urAdapterGetLastError()` takes an adapter handle.

**Comment by kbenzie** [comment]
This seems like a reasonable and simple addition to me.
