### ISSUE TITLE
Add Missing `ur_usm_mem_flags_t` Enumerations

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#116]
# Issue

PI has the [`pi_usm_mem_properties`](https://github.com/intel/llvm/blob/c4932957929f94afe7f87bee009eea5e2b5cd6bf/sycl/include/sycl/detail/pi.h#L571) bitfield which can take the following values:

* `PI_MEM_ALLOC_DEVICE_READ_ONLY`
* `PI_MEM_USM_ALLOC_BUFFER_LOCATION`
used [here](https://github.com/intel/llvm/blob/5b13d5b6d364917c8ef3a7b51ffd01c8be580095/sycl/source/detail/usm/usm_impl.cpp#L184) and [here](https://github.com/intel/llvm/blob/5b13d5b6d364917c8ef3a7b51ffd01c8be580095/sycl/source/detail/usm/usm_impl.cpp#L85) respectively in the DPC++ runtime.

Unified Runtime has the [`ur_usm_mem_flags_t`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L2563) for which there is no equivalent enumeration entries. 

# Task

Add the missing enumeration entries to `ur_usm_mem_flags_t` to meet the requirements for implementing the DPC++ runtime on Unified Runtime.

**Comment by FranklandJack** [comment]
`PI_MEM_USM_ALLOC_BUFFER_LOCATION` doesn't actually have any [usage](https://github.com/intel/llvm/search?q=PI_MEM_USM_ALLOC_BUFFER_LOCATION) in adapters whilst `PI_MEM_ALLOC_DEVICE_READ_ONLY` is only [handled](https://github.com/intel/llvm/blob/179ffa16a929350c86a233ebfcaadc4be2e7be5f/sycl/plugins/level_zero/pi_level_zero.cpp#L8254) in the L0 adapter, so there may be an argument here that these enumerations aren't required after all if these uses can be removed from the DPC++ runtime.

**Comment by igchor** [comment]
There are actually more properties defined in PI: 
https://github.com/intel/llvm/blob/02bc9323e860f5672386db712071fa3277d493b0/sycl/include/sycl/detail/pi.h#L597-L606

Also, similar properties are defined in Level Zero:
https://github.com/oneapi-src/level-zero/blob/4ed13f327d3389285592edcf7598ec3cb2bc712e/include/ze_api.h#LL4253C42-L4253C42

I think we should probably expose them in UR.

**Comment by jandres742** [comment]
@igchor 

> L0 actually has separate flags for device and host allocations: ze_device_mem_alloc_flag_t and ze_host_mem_alloc_flag_t - I'm not sure if we want to do the same.

I think we could have the same set of flags, but applications to those both types above. Reason in L0 there's a ze_device_mem_alloc_flags_t and a ze_host_mem_alloc_flags_t is to be able to set in shared allocation different behavior whether the allocation is in host or the device.

> The last property I listed (UR_MEM_USM_ALLOC_BUFFER_LOCATION) seems to be something similar to device heaps we discussed in https://github.com/oneapi-src/unified-runtime/issues/176 (at least that's my understanding). Here's some description from llvm repo:

The documentation for the CL counterpart is here https://registry.khronos.org/OpenCL/extensions/intel/cl_intel_mem_alloc_buffer_location.html#_overview

This is i think for FPGAs devices, not for GPUs. So maybe needed, but more for an extension?

**Comment by bashbaug** [comment]
I think it would be very wise to have an extensible mechanism to pass additional allocation properties as they are required.  We shouldn't be constrained by a small bitfield.

I don't have a very strong opinion how to do this - it could be an array of property-value pairs like OpenCL, or some sort of structure chaining mechanism like Vulkan and Level Zero, or something else entirely.
