### ISSUE TITLE
Consider whether `ur_device_binary_struct` is required

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#118]
# Issue

The PI interface defines a [`pi_device_binary_struct`](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/include/sycl/detail/pi.h#L796) struct that is (via a `pi_device_binary` alias) is passed through the [`piextDeviceSelectBinary`](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/include/sycl/detail/pi.h#L1046) and [`piProgramCreateWithBinary`](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/include/sycl/detail/pi.h#L1246). 

The `pi_device_binary_struct` type contains various bits of metadata about the binary. There is no equivalent `ur_device_binary_struct` in Unified Runtime, instead [urDeviceSelectBinary](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3032) and [urProgramCreateWithBinary](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3946) take the binary arguments as `uint8_t*`s.

The DPC++ runtime [makes use of the `pi_deivce_binary`](https://github.com/intel/llvm/blob/1c77f9a78a59ecf60bafe5ed73b3878dea96fae1/sycl/source/detail/device_binary_image.hpp#L123) alias. If UR is to be a replacement for PI in the DPC++ runtime we need to decide whether this is a requirement to add to Unified Runtime or not.

If it is decided we need a `ur_device_binary_struct` we may also need to port the associated types and values to UR:
* [`_pi_device_binary_property_struct`](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/include/sycl/detail/pi.h#L696)
* [`_pi_device_binary_property_set_struct`](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/include/sycl/detail/pi.h#L706)
* [`PI_DEVICE_BINARY_VERSION`](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/include/sycl/detail/pi.h#L727)
* [`PI_DEVICE_BINARY_OFFLOAD_KIND_SYCL`](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/include/sycl/detail/pi.h#L730)
* [`pi_device_binaries_struct`](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/include/sycl/detail/pi.h#L893)
* [`PI_DEVICE_BINARIES_VERSION`](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/include/sycl/detail/pi.h#L888)

and the [various target identification strings](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/include/sycl/detail/pi.h#L732-L784).

This is also related to https://github.com/oneapi-src/unified-runtime/issues/95 which adds a metadata parameter to `urProgramCreateWithBinary`. If the parameter is required and added, its type would be `ur_device_binary_property` which would be a field in the `ui_device_binary_property_set` which is in turn would be a field in `ur_device_binary_struct`.

# Task

Investigate whether the above PI API objects need to be ported to the Unified Runtime spec. If they are, port them if not then no action is required.

**Comment by veselypeta** [comment]
Relates to #327
