### ISSUE TITLE
Add missing `ur_device_partition_property_flag_t` entries

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#119]
# Task

PI defined a [`pi_device_partition_property`](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/include/sycl/detail/pi.h#L629) enumeration (as an `intptr_t`) that can take the following values:
* `PI_DEVICE_PARTITION_EQUALLY`
* `PI_DEVICE_PARTITION_BY_COUNTS`
* `PI_DEVICE_PARTITION_BY_COUNTS_LIST_END`
* `PI_DEVICE_PARTITION_BY_AFFINITY_DOMAIN`
* `PI_EXT_INTEL_DEVICE_PARTITION_BY_CSLICE`

UR defines a [`ur_device_partition_property_flag_t`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L2954) enumeration which takes the following values:
* `UR_DEVICE_PARTITION_PROPERTY_FLAG_EQUALLY`
* `UR_DEVICE_PARTITION_PROPERTY_FLAG_BY_COUNTS`
* `UR_DEVICE_PARTITION_PROPERTY_FLAG_BY_AFFINITY_DOMAIN`
* `UR_DEVICE_PARTITION_PROPERTY_FLAG_FORCE_UINT32`

Of the PI values `PI_DEVICE_PARTITION_BY_COUNTS_LIST_END` (which is used [here](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/source/detail/device_impl.cpp#L192)) and `PI_EXT_INTEL_DEVICE_PARTITION_BY_CSLICE` (which is used [here](https://github.com/intel/llvm/blob/5995c61840153b26817ea5b45e7bc0f49b6f4c3e/sycl/source/detail/device_impl.cpp#L265)) are missing from UR.

# Task

Add `UR_DEVICE_PARTITION_BY_COUNTS_LIST_END` and `PI_EXT_INTEL_DEVICE_PARTITION_BY_CSLICE` to Unified Runtime so that it meets the requirements of implementing the DPC++ runtime.

**Comment by FranklandJack** [comment]
On the other hand `PI_EXT_INTEL_DEVICE_PARTITION_BY_CSLICE` does seem to be used in the [L0 adapter](https://github.com/intel/llvm/blob/179ffa16a929350c86a233ebfcaadc4be2e7be5f/sycl/plugins/level_zero/pi_level_zero.cpp#L2988) by `urDeviceGetInfo`. So there is an argument to add that (although the fact it is only used in one adapter might suggest it doesn't need to be in the UR spec?)

**Comment by veselypeta** [comment]
Thanks that makes sense. I may have found another issue with how the `BY_COUNTS` option is defined. In `urDevicePartition` it accepts an array of `ur_device_partition_property_value_t`'s, which is a struct that has two members (1. the property enum, 2. a `uint32_t` for its value). However, this struct would not work for `BY_COUNTS` which expects a zero-terminated array, right?

**Comment by jandres742** [comment]
> On the other hand `PI_EXT_INTEL_DEVICE_PARTITION_BY_CSLICE` does seem to be used in the [L0 adapter](https://github.com/intel/llvm/blob/179ffa16a929350c86a233ebfcaadc4be2e7be5f/sycl/plugins/level_zero/pi_level_zero.cpp#L2988) by `urDeviceGetInfo`. So there is an argument to add that (although the fact it is only used in one adapter might suggest it doesn't need to be in the UR spec?)

@FranklandJack : we have CSLICE because of L0 support for Intel GPUs, do we have a similar concept for other archs that the UR targets? what would be a CSLICE for a CUDA or CPU adapter?

**Comment by kbenzie** [comment]
@jandres742 unfortunately @FranklandJack has moved on and is no working on this project. @veselypeta and I will try and answer your questions although we will need to investigate first.

**Comment by kbenzie** [comment]
https://github.com/intel/llvm/pull/7963 seems to be adding CSLICE to the OpenCL plugin just now but I'm guessing that's for similar reasons to the L0 plugin. I'll continue investigating.

**Comment by jandres742** [comment]
> [intel/llvm#7963](https://github.com/intel/llvm/pull/7963) seems to be adding CSLICE to the OpenCL plugin just now but I'm guessing that's for similar reasons to the L0 plugin. I'll continue investigating.

@kbenzie , You are corrrect.

**Comment by kbenzie** [comment]
@jandres742 I'm struggling to actually determine what cslice device partitioning means. There doesn't appear to be anything in the L0 spec mentioning cslice and the comments I've come across in PI haven't turned on any lightbulbs in my head.

Is there any documentation around what this is/does?

**Comment by jandres742** [comment]
@kbenzie : Now you are seeing my predicament here :)

A c-slice (or slice) in Intel GPU archs contain a single context (or Compute engine). An XE_HPC machine (aka PVC) has 4 slices per sub-device, and two sub-devices in a die (https://www.intel.com/content/www/us/en/develop/documentation/oneapi-gpu-optimization-guide/top/xe-arch.html)

L0 spec allows implementations to divide the target device on any way it see fits, and L0 GPU driver implementation has chosen to have 1 single root device for the die, and 2 sub-devices. L0 GPU driver doesn't expose each slice as another sub-device:

L0 GPU driver:
- 1 root device
- 2 sub-devices, each with 4 compute engines

However, OpenMP and SYCL runtimes wanted to go a bit further, and we defined there another level of sub-devices, each one corresponding to a single slice (so a single compute engine) . See SYCL extension here https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_cslice.asciidoc 

One way of defining then a c-slice is as the finest granular level of compute resource seen by the application, and of course, that would depend on what device the application is targeting.

So, as you see, c-slice is a very specific term, only applicable to intel GPUs, so I would say we should try to make it more generic in the UR, for better adoption of other vendors and devices.

Let me know if this helps.

**Comment by kbenzie** [comment]
Looks like [hipExtStreamCreateWithCUMask](https://docs.amd.com/en-US/bundle/4.5-HIP-API/page/group___stream.html#d41e626) could be doing something analagous, allowing the user to specify a specific compute unit to schedule work on. The interface is quite different but I think the goal is the same.

**Comment by kbenzie** [comment]
CUDA 12 introduced [thread block clusters](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#thread-block-clusters) for compute capability 9.0, which is H100 only.
