### ISSUE TITLE
Support sycl_ext_intel_queue_index extension

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#120]
https://github.com/intel/llvm/pull/7599 introduces support for the `sycl_ext_intel_queue_index` by adding an alternative signature of `piQueueCreate` which allows specifying a null terminated array of queue properties to enable the application to specify the desired queue index for devices which support it. Refer to the extension specification for more detail, and the PR for implementation details.

To resolve this ticket the UR spec should be updated to enable this extension.

**Comment by aelovikov-intel** [comment]
It's needed not only to support the extension, but to support current SYCL implementation at all as the new API is used unconditionally.

**Comment by kbenzie** [comment]
@aelovikov-intel noted, in that case when added to Unified Runtime we'll will ensure it is not optional.
