### ISSUE TITLE
Request to add a new UR API to retrieve global variable pointer from Module

### ISSUE THREAD

**Issue by AllanZyne** [oneapi-src/unified-runtime#1214]
Currently, UR has `urEnqueueDeviceGlobalVariableWrite` and `urEnqueueDeviceGlobalVariableRead` to read and write global variables.
But if developers just want to query if the global variable exists, without reading or writing it, it is impossible now. 

OpenCL and level-zero have this API already.

- OpenCL: `clGetDeviceGlobalVariablePointerINTEL`
- Level-zero:  `zeModuleGetGlobalPointer`

**Comment by kbenzie** [comment]
It appears that for CUDA `cuModuleGetGlobal` would be the equivelent there. This feature is not supported in the HIP adatper for now.

**Comment by kbenzie** [comment]
HIP does have [hipModuleGetGlobal](https://docs.amd.com/projects/HIP/en/docs-5.4.0/doxygen/html/group___memory.html#ga3e425a680285f495e776f096e9632c89) though.
