### ISSUE TITLE
Propose adding a new API "urKernelSuggestGroupSize"

### ISSUE THREAD

**Issue by AllanZyne** [oneapi-src/unified-runtime#1270]
For the sanitizer layer, we need to calculate the total number of workgroups in urEnqueueKernelLaunch. But sometimes, users omit to pass "pLocalWorkSize" parameter, which causes us to be unable to calculate workgroups.

Therefore, I propose adding a new API "urKernelSuggestGroupSize" which will return the LocalWorkSize which is the same as urEnqueueKernelLaunch.

LevelZero has "zeKernelSuggestGroupSize", and OpenCL has "clGetKernelSuggestedLocalWorkSizeKHR". But currently, OpenCL is WIP.

LevelZero 
```cpp
ze_result_t ZE_APICALL
zeKernelSuggestGroupSize(
    ze_kernel_handle_t hKernel,                     ///< [in] handle of the kernel object
    uint32_t globalSizeX,                           ///< [in] global width for X dimension
    uint32_t globalSizeY,                           ///< [in] global width for Y dimension
    uint32_t globalSizeZ,                           ///< [in] global width for Z dimension
    uint32_t* groupSizeX,                           ///< [out] recommended size of group for X dimension
    uint32_t* groupSizeY,                           ///< [out] recommended size of group for Y dimension
    uint32_t* groupSizeZ                            ///< [out] recommended size of group for Z dimension
    );
```

OpenCL 
```cpp
cl_int clGetKernelSuggestedLocalWorkSizeKHR(
cl_command_queue command_queue,
cl_kernel kernel,
cl_uint work_dim,
const size_t* global_work_offset,
const size_t* global_work_size,
size_t* suggested_local_work_size);
```

Proposed prototype:

```cpp
ur_result_t UR_APICALL urKernelSuggestGroupSize(
    ur_queue_handle_t hQueue, ur_kernel_handle_t hKernel, uint32_t workDim,
    const size_t *pGlobalWorkOffset, const size_t *pGlobalWorkSize,
    size_t *pSuggestedLocalWorkSize);
```

**Comment by kbenzie** [comment]
We also need to consider if CUDA and HIP could support this API.

**Comment by npmiller** [comment]
This seems fairly straightforward, I don't envision any issues implementing this for CUDA and HIP since we already need to be able to pick local work size when enqueuing kernels, this would use the same mechanism.

**Comment by yingcong-wu** [comment]
Hi all, I drafted a PR to implement the API in https://github.com/oneapi-src/unified-runtime/pull/1385, would you care to review that PR? Thank you.

**Comment by kbenzie** [comment]
Might be best to take it out of draft, then the reviewer groups will be notified @yingcong-wu.

**Comment by yingcong-wu** [comment]
Sure.

**Comment by AllanZyne** [comment]
Close issue since https://github.com/oneapi-src/unified-runtime/pull/1385 has been merged
