### ISSUE TITLE
loader windows platform discovery implementation

### ISSUE THREAD

**Issue by pbalcer** [oneapi-src/unified-runtime#128]
# issue
The loader needs to be able to discover available adapter implementations, given a hardcoded list of names. On Linux, this is simple since we can rely on dlopen's builtin support for dynamic symbol discovery.
For windows, this gets complicated. The level-zero loader (https://github.com/oneapi-src/level-zero/blob/master/source/loader/windows/driver_discovery_win.cpp) looks for registry keys from the display adapter installation to discover the drivers. This approach might not necessarily work for UR.

# tasks

1. For the time being, we need a simple way of allowing the loader to find adapters on windows. This should include loading hardcoded adapters from some known directory (cwd ?) and support for `UR_ENABLE_ALT_DRIVERS` env variable.
2. We need to figure out and implement the best long-term approach for adapters to register themselves for the loader to discover. Maybe we need a registry folder where adapters info is placed? or maybe have a known single directory for all adapters?

**Comment by kbenzie** [comment]
As a data point, the OpenCL-ICD-Loader defines a similar approach [here](https://github.com/KhronosGroup/OpenCL-ICD-Loader#registering-icds) of using a config file on Linux and registry keys on Windows.

**Comment by pbalcer** [comment]
We've discussed this at the workgroup, and the decision is to keep things simple for now. The hard coded list of adapters will stay and be used on both platforms. In addition, we will:
 - create a new env variable (`UR_ADAPTERS_SEARCH_PATH`) that specifies a comma-separated list of directories to include in the adapter search. This can be implemented in a platform-agnostic way with the use of `std::filesystem` (because I don't think there's a clean way of adding a library search path on Linux. `LD_LIBRARY_PATH` needs to be defined on program start).
 - make the loader look for adapters in the loader's own location. This can be accomplished on Linux with `dlinfo(..., RTLD_DI_LINKMAP, ...);` and on Windows with `GetModuleFileName`.
