### ISSUE TITLE
[docs] Can the word "etor" de replaced by a more consice, clear word?

### ISSUE THREAD

**Issue by yingcong-wu** [oneapi-src/unified-runtime#1381]
Hi,
I am reading https://github.com/oneapi-src/unified-runtime/blob/main/scripts/YaML.md#input-structure and I find the word "etor" confusing. I don't understand what it means and after some searching, I still cannot find some answers. Is it an acronym like ctor, dtor, xtor for C++?

Also, considering this is a document for the project instead of some comments in the code, shouldn't we use more clear words for this to help reader better understand the content?

**Comment by pbalcer** [comment]
It's a short for **e**numera**tor**. It stumped me a little too when I first saw it, but I'm not sure whether replacing it in the spec is practical. But I agree that it might be a good improve the docs.

**Comment by yingcong-wu** [comment]
Okay, that is the first time I heard about that word. Thanks for the answer.
I think for a word that is not widely used(to my knowledge), we should at least write a comment or an explanation for that. That is more practical than replacing etor in the spec, right?

**Comment by kbenzie** [comment]
@yingcong-wu we can certainly improve the docs to make it clearer what `etor` means in this context.

**Comment by yingcong-wu** [comment]
Thank you!
