### ISSUE TITLE
[L0] UR_PROGRAM_INFO_DEVICES is unimplementable for urProgramCreateWithNativeHandle

### ISSUE THREAD

**Issue by pbalcer** [oneapi-src/unified-runtime#1384]
```
enumerator UR_PROGRAM_INFO_DEVICES
[ur_device_handle_t[]] Return list of devices associated with Program.
```

This is currently unimplementable for programs that are created using `urProgramCreateWithNativeHandle` because there doesn't appear to be a way to retrieve a list of devices from L0 for a module (see [L0 docs](https://spec.oneapi.io/level-zero/latest/core/PROG.html#modules-and-kernels)) nor does this function take a list of devices we could just store.

As far as I can tell, we don't even have device information in [SYCL](https://github.com/intel/llvm/blob/sycl/sycl/source/detail/program_impl.cpp#L134). Instead, SYCL relies on exactly `UR_PROGRAM_INFO_DEVICES` to populate its list of devices in the `program_impl` class.

I don't think there are any user-visible issues, performance or functional, related to this in SYCL right now, but we might want to consider returning 0 devices or some error status for this case.

**Comment by kbenzie** [comment]
`urProgramCreateWithNativeHandle` takes a `ur_context_handle_t` which could be used to populate the device list.

**Comment by kbenzie** [comment]
If that's not the desired set of devices, then we'd likely need to require the user to provide the device list when calling `urProgramCreateWithNativeHandle`.

**Comment by pbalcer** [comment]
But can't a module be built for a subset of devices in a context?

**Comment by pbalcer** [comment]
> If that's not the desired set of devices, then we'd likely need to require the user to provide the device list when calling `urProgramCreateWithNativeHandle`.

I think that would require the SYCL API to change.

**Comment by kbenzie** [comment]
> But can't a module be built for a subset of devices in a context?

It can, that's different the the list of devices associated with the program though. The list of associated devices is all the devices the program *can* be built for.

**Comment by pbalcer** [comment]
> > But can't a module be built for a subset of devices in a context?
> 
> It can, that's different to the list of devices associated with the program though. The list of associated devices is all the devices the program _can_ be built for.

Gotcha, I was misled by this comment "return true number of devices this program exists for." in the current L0 implementation. So, generally, is UR_PROGRAM_INFO_DEVICES just a shorthand for `UR_PROGRAM_INFO_CONTEXT` -> `UR_CONTEXT_INFO_DEVICES` ?

We found this with @nrspruit in a real application when SYCL was hitting this assert: https://github.com/intel/llvm/blob/sycl/sycl/source/detail/program_impl.cpp#L164

The problem ended up being that `MContext->getPlatformImpl()->get_devices();` didn't return the correct devices, but this code seems to suggest that there might be some difference between the set of devices in a platform, the devices in the context, and finally the devices associated with the program. Otherwise, why not just `MContext->get_devices()` ?

**Comment by pbalcer** [comment]
> CL_PROGRAM_DEVICES
> 
> cl_device_id[]
> 
> Return the list of devices associated with the program object. This can be the devices associated with context on which the program object has been created or can be a subset of devices that are specified when a program object is created using clCreateProgramWithBinary.
> 
from https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/clGetProgramInfo.html

OpenCL has better docs than UR :-)

Based on this, I believe `UR_PROGRAM_INFO_DEVICES` should return all devices in the context for urProgramCreateWithNativeHandle.

**Comment by kbenzie** [comment]
We will clarify the UR spec to align with the OpenCL spec on this.
