### ISSUE TITLE
Recondisder urKernelSetArg

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#14]
`urKernelSetArg` appears to have been heavily influenced by the `clSetKernelArgs` OpenCL API.

The `clSetKernelArgs` entry point is problematic for two reasons:
1. It is [one of the only non-thread safe APIs in OpenCL](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_multiple_host_threads), this behavior seems to have been inherited by `urKernelSetArg`:
```
   * The application must not call this function from simultaneous threads with the same kernel handle.

   * The implementation of this function should be lock-free.
```
2. It only sets one argument at a time.

We should be careful about repeating history here. Firstly, the API should be thread safe unless there is a valid reason it can't be, second we should support an API that sets multiple kernel arguments at once since this may be more optimal on some platforms.

**Comment by kbenzie** [comment]
This might already be done but we should check if it that is in fact the case. I believe the `void*` version was removed from the spec already.
