### ISSUE TITLE
cudaOccupancyMaxActiveBlocksPerMultiprocessor

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/unified-runtime#1424]
Is there a SYCL function for  cudaOccupancyMaxActiveBlocksPerMultiprocessor ? some use cases are listed below. Thanks.

AITemplate/3rdparty/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:    result = cudaOccupancyMaxActiveBlocksPerMultiprocessor(
AITemplate/3rdparty/cutlass/include/cutlass/gemm/device/gemm_universal_base.h:    cudart_result = cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(
AITemplate/3rdparty/cutlass/include/cutlass/gemm/device/gemm_universal_base.h:      CUTLASS_TRACE_HOST("  cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags() returned error " << cudaGetErrorString(cudart_result));
AITemplate/3rdparty/cutlass/include/cutlass/gemm/device/base_grouped.h:    result = 
AITemplate/3rdparty/cub/cub/device/dispatch/dispatch_radix_sort.cuh:            if (CubDebug(error = cudaOccupancyMaxActiveBlocksPerMultiprocessor(
AITemplate/3rdparty/cub/cub/util_device.cuh:    return CubDebug(cudaOccupancyMaxActiveBlocksPerMultiprocessor(
AITemplate/python/aitemplate/backend/cuda/groupnorm/layer_norm.cuh:    cudaError_t err = cudaOccupancyMaxActiveBlocksPerMultiprocessor(
AITemplate/python/aitemplate/backend/cuda/layernorm_sigmoid_mul/layer_norm.cuh:    cudaError_t err = =
AITemplate/python/aitemplate/backend/cuda/softmax/softmax.cuh:  cudaOccupancyMaxActiveBlocksPerMultiprocessor(

**Comment by GeorgeWeb** [comment]
Hi @jinz2014 . Working on this, I'll ping you when a PR is up. Thank you!

**Comment by jinz2014** [comment]
Thanks. This will enable the migration of variants of the function in the SYCL compiler.

**Comment by npmiller** [comment]
This has been implemented in:
* UR: https://github.com/oneapi-src/unified-runtime/pull/1796
* DPC++: https://github.com/intel/llvm/pull/14333

Which should make it possible to get the same information, we're also investigating some SYCL compat changes to make it easier to port from CUDA.
