### ISSUE TITLE
Fuzz tests segfaulting

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#1435]
In the last day or so the *Build and run quick fuzztest scenarios* tests have been occasionally failing with segfaults.

* #1431 [here](https://github.com/oneapi-src/unified-runtime/actions/runs/8259996916/job/22594778917?pr=1431)
* #1353 [here](https://github.com/oneapi-src/unified-runtime/actions/runs/8265640090/job/22611754978?pr=1353)

Using this issue to monitor these failures and discuss solutions.

**Comment by pbalcer** [comment]
@PatKamin ping.

This is new, so it's possible that the fuzzer is detecting some issue (or our env is broken).

**Comment by PatKamin** [comment]
I will try to reproduce it locally. It's also worth having some more logs from these short runs in the meantime by having a verbose output. I'll create a PR for that.

**Comment by PatKamin** [comment]
Locally I can't reproduce this. These fails, however, happen only when jobs are ran on the newest version of the `ubuntu-22.04` GitHub-hosted runner: 20240310.1.0. There is an issue filed in the runners repo: https://github.com/actions/runner-images/issues/9491 . This might be related as we use ASAN and UBSAN in fuzztest jobs (and we don't use sanitizers in any other job). 

We have problems with this Ubuntu runner also in the UMF repo, also during builds with sanitizers enabled.
