### ISSUE TITLE
Reconsider urEventCreate

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#15]
`urEventCreate` appears to be inspired by the [`clCreateUserEvent`](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clCreateUserEvent) API.

OpenCL user events can be painful to implement since they essentially require bidirectional host-device synchronization, which may not be something a platform can efficiently support. We should consider whether user events are really required in the Unified Runtime API and if not remove this entry point.

**Comment by kbenzie** [comment]
Based on WG discussion intent is to completely remove support for user events.
