### ISSUE TITLE
performance issue  stream create, copy, destroy 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/unified-runtime#1589]
There is some performance gap between the cuda and dpct programs when they run on an NVIDIA GPU (e.g. 3090). The performance gap is introduced by SYCL runtime (https://github.com/oneapi-src/SYCLomatic/issues/1941). Thanks.

DPCT program:https://github.com/zjin-lcf/HeCBench/blob/master/src/streamCreateCopyDestroy-sycl/main.cpp
Create+Copy+Synchronize+Destroy time for 1 streams and 5000 buffers  and   16 iterations 17.0295 (ms)
Create+Copy+Synchronize+Destroy time for 2 streams and 5000 buffers  and    8 iterations 17.0324 (ms)
Create+Copy+Synchronize+Destroy time for 4 streams and 5000 buffers  and    4 iterations 17.0522 (ms)
Create+Copy+Synchronize+Destroy time for 8 streams and 5000 buffers  and    2 iterations 16.9666 (ms)

CUDA program: https://github.com/zjin-lcf/HeCBench/blob/master/src/streamCreateCopyDestroy-cuda/main.cu
Create+Copy+Synchronize+Destroy time for 1 streams and 5000 buffers  and   16 iterations 12.8682 (ms)
Create+Copy+Synchronize+Destroy time for 2 streams and 5000 buffers  and    8 iterations 12.799 (ms)
Create+Copy+Synchronize+Destroy time for 4 streams and 5000 buffers  and    4 iterations 12.815 (ms)
Create+Copy+Synchronize+Destroy time for 8 streams and 5000 buffers  and    2 iterations 12.8682 (ms)

**Comment by npmiller** [comment]
This is creating a regular SYCL queue, so it will be out-of-order and also have events for all enqueued commands.

To compare with CUDA an in-order SYCL queue with discard events should be more accurate, for example with:

```diff
diff --git a/src/streamCreateCopyDestroy-sycl/main.cpp b/src/streamCreateCopyDestroy-sycl/main.cpp
index e3bdddcf..6a50b9a7 100644
--- a/src/streamCreateCopyDestroy-sycl/main.cpp
+++ b/src/streamCreateCopyDestroy-sycl/main.cpp
@@ -69,7 +69,9 @@ void PerfStreamCreateCopyDestroy::run(unsigned int testNumber) {
 
   for (size_t i = 0; i < iter; ++i) {
     for (size_t s = 0; s < numStreams_; ++s) {
-      streams[s] = device.create_queue();
+      streams[s] = new sycl::queue(device,
+          sycl::property_list{sycl::property::queue::in_order(),
+          sycl::ext::oneapi::property::queue::discard_events()});
     }
 
     for (size_t s = 0; s < numStreams_; ++s) {
```

I get comparable results between CUDA and SYCL.

The benchmark should be switched to using in-order queues, I'm not sure if it's possible to pass discard events to dpct but we also have on-going work to improve the overhead from events in SYCL so when that comes through hopefully the property won't be needed.
