### ISSUE TITLE
Add get-last-error functionality

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#16]
The PI plugin layer has an API for querying the last error from a plugin implementation/adapter e.g. https://github.com/intel/llvm/blob/sycl/sycl/plugins/opencl/pi_opencl.cpp#L87.  To get parity with PI we will need to add something like this to unified runtime.

Initially we could just have an API that matches that in PI i.e.
```
ur_result_t zerGetLastError(char **message);
```
where the returned value is the last reported error code and `message` is an out parameter which is set to point at some adapter specific string containing a detailed message about the context of the error value.

This approach isn't ideal, since the memory returned is owned by the adapter so any caller would need to make a copy of the returned string if they want it to remain consistent, concurrent accesses may also be problematic and in the above declaration there is no way to get the size of the memory without assuming the string is null terminated, so these things would all need to be documented in the spec. In general though this is a tricky problem to solve with a C API.

**Comment by FranklandJack** [comment]
Yeah I think that is a good idea, I didn't want to deviate too much from the `piGetLastError` signature, but I did think about this and it would solve some of the above issues.

So something like:
```
 zer_result_t zerGetLastError(zer_result_t* out_result, char *message, size *message_size);
```
With intended usage like:
```
// some Unified Runtime code which might result in an error...
zer_result_t previous_error = ZER_RESULT_SUCCESS;
size_t message_length = 0;
zer_result_t result_of_call_to_getLastError = zerGetLastError(&previous_error, NULL, &message_length);
if (ZER_RESULT_SUCCESS != result_of_call_to_getLastError) {
 // error out
}

if (ZER_RESULT_SUCCESS != previous_error) {
char * message = malloc(message_length);
  // check allocation succeeded.
  result_of_call_to_getLastError = zerGetLastError(NULL, message, NULL);
  if (ZER_RESULT_SUCCESS != result_of_call_to_getLastError) {
    // error out
  }
  // do stuff with error message.
}
}
```
Is that the sort of thing you had in mind?

In OpenCL APIs that may return a variable sized output typically also take a `param_value_size` argument e.g. clGetDeviceInfo:
```
cl_int clGetDeviceInfo(
    cl_device_id device,
    cl_device_info param_name,
    size_t param_value_size,
    void* param_value,
    size_t* param_value_size_ret);
```
takes a `param_value_size` which is passed in with the allocated memory at `param_value` for array outputs so the implementation knows how big the allocated region is and can return an error if the size of the memory is insufficient. Should we consider adding something like this too? 


I guess the biggest concern with this is that it typical usage requires memory allocation on the part of the user, so if this is then propagated up the stack with something like an exception this design is somewhat prone to memory leaks, although I guess that is the responsibility of the caller and C++ should make this a lot safer if instead we throw something wrapping a `std::string` for example.

**Comment by kbenzie** [comment]
> I guess the biggest concern with this is that it typical usage requires memory allocation on the part of the user, so if this is then propagated up the stack with something like an exception this design is somewhat prone to memory leaks, although I guess that is the responsibility of the caller and C++ should make this a lot safer if instead we throw something wrapping a `std::string` for example.

I think giving the responsibility of owning storage for these error messages to the caller is preferable to UR owning the storage, though.

The (size, value) two call approach gets my vote.

**Comment by FranklandJack** [comment]
This call twice pattern is slightly problematic if the intention is for this API to also be able to return an error code.

For example, if I call API `foo` which returns an error code (say `A`), then I call `zerGetLastError` (which currently also returns an error code, say `B`) to query the message size, then a second time to write into some buffer I have allocated which error does the second call to `zerGetLastError` refer to, the call to `foo` (so `A`) or the call to `zerGetLastError` (so `B`)?

I guess we could either have `zerGetlastError` not return anything (`void`, I think this is what PI currently does), but then there would be no way to communicate if something went wrong during its execution e.g. the buffer passed to the API isn't big enough for the message. Or we could specify that calls to `zerGetLastError` don't affect the *last error*.

**Comment by kbenzie** [comment]
We still need an error code but for validation of the arguments we are given, I don't think it should be the underlying error code, that should be described in the message.

The reason this entry point gets called is because another entry point already returned an error and the user wants more information in the form of a message.

I'm not sure how PI currently does it but if I were implementing an adapter I'd have include the underlying error code in the error message along with the string form of it.

**Comment by FranklandJack** [comment]
PI has the [following](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/detail/pi.h#L1791-L1801):
```
/// API to get Plugin specific warning and error messages.
/// \param message is a returned address to the first element in the message the
/// plugin owns the error message string. The string is thread-local. As a
/// result, different threads may return different errors. A message is
/// overwritten by the following error or warning that is produced within the
/// given thread. The memory is cleaned up at the end of the thread's lifetime.
///
/// \return PI_SUCCESS if plugin is indicating non-fatal warning. Any other
/// error code indicates that plugin considers this to be a fatal error and the
/// runtime must handle it or end the application.
__SYCL_EXPORT pi_result piPluginGetLastError(char **message);
```

which to me sounds like the returned error code is the last error code, not the result of calling `piPluginGetLastError` itself. If this is the case, I think we do need a way to return the last error to the caller as well as the result of calling the entry point itself.

**Comment by pbalcer** [comment]
Most C libraries I've seen take approaches similar to [`errno`](https://man7.org/linux/man-pages/man3/errno.3.html) and [`strerror`](https://man7.org/linux/man-pages/man3/strerror.3.html) - the application first checks if there's an error and follows it up with a call to a function that returns a string error message. In things I've worked on before, we had a separate errnum-checking mechanism and a function that returns a `const char *` pointer to a thread-local string error message, similar to PI's approach. That's much less boilerplate for developers to deal with.
```
if (ur_errnum() != 0) {
  fprintf(stderr, "Unified Runtime error: %s", ur_errstr());
}
```

**Comment by AerialMantis** [comment]
Yeah this is what I had in mind, I also agree that having the caller responsible for allocation is preferable.

I think you're right, if we go for the two call approach it makes sense that we have both the error code from calling the API to report whether the API was called successfully, since there's a possibility for user error, and also the error code from the last error.

There would be the interesting situation where the user calls some API which results in an error, then calls `piPluginGetLastError` to get the size and that produces an error, so the next call to `piPluginGetLastError` will be for the first call to `piPluginGetLastError`, but the user should check the result of the first call.

**Comment by AidanBeltonS** [comment]
So the goal of this function was to allow the `plugin` to emit a backend specific error/warning message without blowing up the number of error codes. The function `piPluginGetLastError` does not return the previous error code (I think there is a strong argument to rename this function as it is quite misleading). If a given PI call returns `PI_ERROR_PLUGIN_SPECIFIC_ERROR` then the user can retrieve the backend specific error message with `piPluginGetLastError`. An error code is returned with the message to indicate if the message is a warning or an error. `PI_SUCCESS` for warning, anything else is considered an error.

Both the returned error code and message are thread local. See: https://github.com/intel/llvm/blob/sycl/sycl/plugins/cuda/pi_cuda.cpp#L66-L67. This means the thread which gets the error/warning can safely retrieve the message without worrying about other threads. This may address your issue regarding the memory not being consistent. So the only thread that can/should touch that memory is the thread which triggered the backend specific error.

This is an example of its use case with prefetch: https://github.com/intel/llvm/blob/sycl/sycl/plugins/cuda/pi_cuda.cpp#L5125-L5181
In CUDA we cannot use prefetch on windows and if the memory is not concurrently accessed memory. As opposed to killing the program (which would cause us to fail some SYCL CTS tests) we emit a performance warning that the user is wasting calls to the plugin which cannot execute the requested hint.

**Comment by kbenzie** [comment]
@AidanBeltonS given you think there's a strong argument for renaming this function, do you have any recommendations of a less misleading name?

**Comment by AidanBeltonS** [comment]
Perhaps `piPluginGetLastSpecificError`? This makes it clear that it is a specific error not just the previous error code and that it is related to the `PI_ERROR_PLUGIN_SPECIFIC_ERROR` error code.

**Comment by FranklandJack** [comment]
@AidanBeltonS thanks for the explanation on this, I think it has made things clearer. Just to clarify, the expect usage would go something like:
```
const auto error = urSomeAPI(...);
if (PI_ERROR_PLUGIN_SPECIFIC_ERROR == error) {
  const char *plugin_specific_error  = NULL;
  const auto is_fatal_error = urPluginGetLastSpecficError(plugin_specific_error);
  
  if (PI_SUCCESS == is_fatal_error) {
    // handle plugin_specific_error as warning...
  } else {
    //  handle plugin_specific_error as error (e.g. throw exception with plugin_specific_error string) ...
  }
}
```
And for regular errors, e.g. say you passed some invalid parameters to an API that then returned `UR_RESULT_INVALID_VALUE` that wouldn't *set the last error* to `UR_RESULT_INVALID_VALUE`, this is only for platform specific error codes and it is a way to return them as a string without having to specify them all in backend specific enums?

**Comment by AidanBeltonS** [comment]
Yes, that is the expected usage. Also your understanding with regards to regular error codes is correct, a returned `UR_RESULT_INVALID_VALUE` error code would not set the last error to `UR_RESULT_INVALID_VALUE`.
