### ISSUE TITLE
Add tests for `urDevicePartion` with `BY_COUNTS` and `BY_AFFINITY_DOMAIN`

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#169]
We should add additional testing for device partitioning, specifically with `UR_DEVICE_PARTITION_PROPERTY_FLAG_BY_COUNTS` & `UR_DEVICE_PARTITION_PROPERTY_FLAG_BY_AFFINITY_DOMAIN`.

This is blocked until #119 is resolved.

**Comment by kbenzie** [comment]
@fabiomestre is working on this

**Comment by fabiomestre** [comment]
Done in https://github.com/oneapi-src/unified-runtime/pull/214
