### ISSUE TITLE
GHA Windows 2022 Release failures

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#1715]
Looks like we have an issue on Windows 2022 jobs in Release mode, doesn't seem to matter what the other matrix axes are. Its causing these failures:

```
The following tests FAILED:
	  5 - umf-disjointPool (SEGFAULT)
	 23 - loader_platform_test_no_platforms (Failed)
	 24 - loader_platform_test_null_platform (Failed)
	 25 - loader-handles (Failed)
	 27 - parameters (Failed)
	 28 - leaks (Failed)
	 29 - leaks_mt (Failed)
	 30 - lifetime (Failed)
	 31 - example-collected-hello-world (Failed)
	 32 - example-logged-hello-world (Failed)
	 33 - codeloc (Failed)
	 37 - unit-logger (SEGFAULT)
	 38 - unit-logger_env_var_default_flush_lvl_err_msg-validate-output (Failed)
	 40 - unit-logger_env_var_default_flush_lvl_all_lvls_msg-validate-output (Failed)
	 41 - unit-logger_env_var_stdout_basic-validate-output (Failed)
	 42 - unit-logger_env_var_stderr_basic-validate-output (Failed)
	 45 - unit-logger_env_var_default_output_stderr_2-validate-output (Failed)
	 48 - unit-logger_env_var_lvl_debug-validate-output (Failed)
	 49 - unit-logger_env_var_lvl_info-validate-output (Failed)
	 50 - unit-logger_env_var_lvl_info_err_msg-validate-output (Failed)
	 52 - unit-logger_env_var_lvl_warning-validate-output (Failed)
	 53 - unit-logger_env_var_lvl_warning_err_msg-validate-output (Failed)
	 55 - unit-logger_env_var_lvl_error-validate-output (Failed)
	 89 - trace_test_null_hello (Failed)
	 90 - trace_test_null_hello_no_args (Failed)
	 91 - trace_test_null_hello_filter_device (Failed)
	 92 - trace_test_null_hello_profiling (Failed)
	 93 - trace_test_null_hello_begin (Failed)
	 94 - trace_test_null_hello_json (Failed)
```

There are multiple instances of this:

* https://github.com/oneapi-src/unified-runtime/actions/runs/9382215236/job/25833181921?pr=1714#logs
* https://github.com/oneapi-src/unified-runtime/actions/runs/9383285470/job/25836564263
* https://github.com/oneapi-src/unified-runtime/actions/runs/9382292727/job/25833428359
* https://github.com/oneapi-src/unified-runtime/actions/runs/9375542621/job/25834320306?pr=1697

**Comment by kbenzie** [comment]
The failures seem to not be consistent and a retry can often make the workflow green.

**Comment by kbenzie** [comment]
The failures are across different axes of the matrix config:

* Build - Windows (windows-2022, None, Release, cl, cl) - https://github.com/oneapi-src/unified-runtime/actions/runs/9382215236/job/25833181921?pr=1714
* Build - Windows (windows-2022, None, Release, clang-cl, clang-cl) - https://github.com/oneapi-src/unified-runtime/actions/runs/9383285470/job/25836564263
* Build - Windows (windows-2022, L0, -DUR_BUILD_ADAPTER_L0=ON, Release, cl, cl) - https://github.com/oneapi-src/unified-runtime/actions/runs/9382292727/job/25833428359

Which would make temporarily excluding the failing configs remove most/all of the Windows Server 2022 Releas mode testing. That's not ideal.

**Comment by kbenzie** [comment]
The linked failing jobs were all on runner version 2.316.1 - recent passing jobs were on 2.317.0. Will dig deeper to see if this was a runner issue all along.

**Comment by kbenzie** [comment]
https://github.com/oneapi-src/unified-runtime/actions/runs/9398852341/job/25886602078 failed on 2.317.0 so its not that.

**Comment by kbenzie** [comment]
@lukaszstolarczuk did you reenable these configs?

**Comment by lukaszstolarczuk** [comment]
yeah, it was merged here: https://github.com/oneapi-src/unified-runtime/pull/1827

Builds seem stable now, so we can close this issue, I guess.
