### ISSUE TITLE
Left shift cause undefined behavior if offset is 64-bit.

### ISSUE THREAD

**Issue by CaoZhongZ** [oneapi-src/unified-runtime#1825]
Will be undefined if 'kernelTimestampValidBits' is 64-bit.

https://github.com/oneapi-src/unified-runtime/blob/40300808bc20e35d71a6d034b32619ee31512985/source/adapters/level_zero/event.cpp#L497-L498

**Comment by nrspruit** [comment]
fixed by https://github.com/oneapi-src/unified-runtime/pull/1806
