### ISSUE TITLE
Clarify how device partitioning properties are terminated

### ISSUE THREAD

**Issue by smaslov-intel** [oneapi-src/unified-runtime#183]
In https://github.com/oneapi-src/unified-runtime/blob/00b8fd6aef508d8bd83089322d9ae0b84f647e6c/include/ur_api.h#L3138
///< [in] null-terminated array of <property, value> pair of the requested partitioning.

But the input is an array of struct {uint32_t, uint32_t}, so there is no pointer to indicate end of the array.

**Comment by veselypeta** [comment]
#119 may be relevant

**Comment by kbenzie** [comment]
If we keep the struct it should be an `intptr_t`.

**Comment by kbenzie** [comment]
Resolution is to change to make UR match what PI has today.
