### ISSUE TITLE
CUDA out-of-memory error in SYCL programs and not in CUDA programs

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/unified-runtime#1832]
Running the two SYCL programs below causes CUDA out-of-memory errors. Runing the corresponding CUDA programs is successful.  

https://github.com/zjin-lcf/HeCBench/tree/master/src/ace-sycl
https://github.com/zjin-lcf/HeCBench/tree/master/src/glu-sycl

You may reproduce the errors with the command like:
python autohecbench.py  ace-sycl  --compiler-name icpx --nvidia-sm 75

software: oneAPI CUDA plugin for oneAPI 2024.2.0
hardware: Nvidia Geforce RTX2080 (8GB)

**Comment by al42and** [comment]
Are you sure the CUDA version works? If I'm not mistaken, with 600³ grid, the `vol_in_bytes` is 600*600*600*8 = 1728000000, and there are 7 such allocations on the device, which requires in total ~11.5GB, more than the total memory of your device.

**Comment by zjin-lcf** [comment]
Thank you for explaining the issue. I will update the example for the memory issue.
