### ISSUE TITLE
MemAdvice being used instead of MemAdvise as in other APIs

### ISSUE THREAD

**Issue by jandres742** [oneapi-src/unified-runtime#187]
Advise (verb) instead of advice (noun) is used in other APIs ("MemAdvise sets an Advice"). See

https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1ge37112fc1ac88d0f6bab7a945e48760a

https://spec.oneapi.io/level-zero/latest/core/api.html?highlight=advise#_CPPv428zeCommandListAppendMemAdvise24ze_command_list_handle_t18ze_device_handle_tPKv6size_t18ze_memory_advice_t

But here we have only the noun. Minor thing but still :)

https://github.com/oneapi-src/unified-runtime/blob/746786d6c223005335de7939127c413a8411fb9c/include/ur_api.h#L1296 

Dont know if we could change it w/o breaking compatibility.

**Comment by kbenzie** [comment]
@jandres742 we are not making any ABI stability guarnetees yet so we can still make this change. 👍 for consisitency with other APIs.

**Comment by alycm** [comment]
I kept on misreading this as advice when looking at it yesterday, so I agree on going for consistency.
