### ISSUE TITLE
Fuzz Tests Segfaulting

### ISSUE THREAD

**Issue by isaacault** [oneapi-src/unified-runtime#1935]
Fuzz tests are failing with segfaults. It seems to be inconsistent which specific tests segfault, but the CI job failing is seemingly consistent.

Perhaps related to https://github.com/oneapi-src/unified-runtime/issues/1435.

Examples:

- https://github.com/oneapi-src/unified-runtime/actions/runs/10250514470/job/28356417298?pr=1928#logs
- https://github.com/oneapi-src/unified-runtime/actions/runs/10261541421/job/28389476299?pr=1934
- https://github.com/oneapi-src/unified-runtime/actions/runs/10257624752/job/28378999837?pr=1933
- https://github.com/oneapi-src/unified-runtime/actions/runs/10255117181/job/28371382785?pr=1932

**Comment by pbalcer** [comment]
We suspect this is a problem with disabling deepbind (required to run the fuzz test under asan) in the L0 driver. For the time being we will be disabling asan.

**Comment by PatKamin** [comment]
This could be related with this issue: https://github.com/oneapi-src/unified-runtime/blob/main/.github/workflows/build-fuzz-reusable.yml#L24-L25. The current workaround is not persistent after a reboot of a server on which CI runs. The `vm.mmap_rnd_bits` value has been set to 28 now, and the GPU drivers has been updated.

Currently @ldorau is working on installing a version of a clang compiler that has the issue fixed on these CI servers.

**Comment by PatKamin** [comment]
The issue should be resolved now, clang version 18.1.8 is installed on the given servers. Let's observe the short fuzztests that are run in each PR and disable temporarily sanitizers in the nightly tests only.

**Comment by ldorau** [comment]
I already installed Clang v18.1.8 on the CI servers.

**Comment by pbalcer** [comment]
Fuzz tests are passing in CI: https://github.com/oneapi-src/unified-runtime/actions/runs/10264968242/job/28400161804

thanks.
