### ISSUE TITLE
[L0] Delete-type-mismatch output in asan

### ISSUE THREAD

**Issue by fabiomestre** [oneapi-src/unified-runtime#1942]
While trying to run asan on a graph e2e test, I found an issue that seems to be related to the v2 version of the level-zero adapter. There is a new context class for v2  but delete is being called on the base class which causes a delete-type-mismatch error in asan. I don't think this is causing any major bugs but, technically, it is to be undefined behaviour. This is the asan output: [asan_output.txt](https://github.com/user-attachments/files/16511724/asan_output.txt)

**Comment by igchor** [comment]
This should be fixed after https://github.com/oneapi-src/unified-runtime/pull/1913 v2::context no longer inherits from the legacy context and they are completely separated.
