### ISSUE TITLE
Consider relaxing ur_module_handle_t SPIR-V requirement

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#20]
There seems to be an implicit requirement that `ur_module_handle_t` objects are SPIR-V modules. From the [`urProgramCreate`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3712) entry point:

```
Create Program from input SPIR-V modules. 
```

Do we want to restrict the `ur_module_handle_t` objects to contain SPIR-V only. Or is it possible that higher level language runtimes sitting on top of Unified Runtime could feed it non SPIR-V based intermediate representations for compilation to target specific executables in the adapter via the `urModuleCreate` -> `urProgramCreate` path?

**Comment by aarongreig** [comment]
all references to SPIR-V are replaced with generic references to "IL" in https://github.com/oneapi-src/unified-runtime/pull/250
