### ISSUE TITLE
Add missing enumartions for device types

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#204]
In #200 we removed `ur_platform_init_flags_t` parameter from `urInit` since we handle platform discovery and selection through the loader. In fact the loader does nothing with either of these two input flags, which raises the question if `ur_device_init_flags_t`. 

We should determine if device flags actually have any use or purpose and if not remove this additional parameter.

**Comment by jandres742** [comment]
maybe we dont have at this moment, but maybe we could have in the future? we might find out we need initialization flags to change a behavior in the UR globally?

**Comment by veselypeta** [comment]
From last weeks WG there was some discussion about the `ONEAPI_DEVICE_SELECTOR` environment variable. And we wanted to move this into UR to prevent duplication across SYCL and OpenMP (which doens't have it implemented yet). Could this parameter be useful for passing the parsed results from SYCL to UR?

**Comment by jandres742** [comment]
@veselypeta maybe? ONEAPI_DEVICE_SELECTOR selects several things, like backend (L0, OCL, CUDA), device (GPU, CPU), topology to expose, among other things.
At least device type could be passed as a flag to urInit.

BTW, how is that we have only GPU for urInit, but FPGA, CPU, ACC, VPU, in urDeviceGet

this is like saying you can initialize only GPU, but maybe the device (after initialization) could be something else :)

**Comment by kbenzie** [comment]
`ur_device_init_flags_t` also does not have an enumeration for the default of `0` to enable all devices.

I think this should be repurposed into fleshing out the `ur_device_init_flags_t` enum to have all the relevant devices types.

**Comment by veselypeta** [comment]
I'm not sure i understand the difference between:
[`ur_device_init_flag_t`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L286) - missing enumerations
[`ur_device_type_t`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L286) - has all enumerations

Could we have `urInit()` take `ur_device_type_t` instead of `ur_device_init_flag_`?

**Comment by kbenzie** [comment]
I think that's a pretty reasonable approach, yeah.

**Comment by kbenzie** [comment]
I think `urInit()` should be accepting multiple device types though, in a `uint32_t` bit field.
