### ISSUE TITLE
`urEnqueue*` entry points should return  `UR_RESULT_ERROR_INVALID_EVENT_WAIT_LIST`

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#219]
`urEnqueue*` entry-points that take event wait list and count parameters should return the error code `UR_RESULT_ERROR_INVALID_EVENT_WAIT_LIST` under the following conditions.

* If `phEventWaitList` == NULL && `numEventsInWaitList` >0
* if `phEventWaitList` != NULL && `numEventsInWaitList` == 0

We should also add conformance tests to the enqueue testsuite to check for this

**Comment by fabiomestre** [comment]
Done in https://github.com/oneapi-src/unified-runtime/pull/286
