### ISSUE TITLE
Adds CTS tests for `urMemGetNativeHandle` entry-point

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#229]
We should add conformance tests for `urMemGetNativeHandle`.

Required Coverage:
* At least one successful (i.e. called with correct arguments and assert on expected result, not applicable to `CreateWithNativeHandle` entry points)
* If this a query entry-point or one which accepts flags etc : we should tests every possible enumeration (where possible).
* A test case for each returned error code (exclude disaster situations i.e. OUT_OF_MEMORY etc)

**Comment by kbenzie** [comment]
@martygrant is looking at this

**Comment by martygrant** [comment]
Done in #262
