### ISSUE TITLE
Adds CTS tests for `urEnqeueuKernelLaunch` entry-point

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#234]
We should add conformance tests for `urEventCreateWithNativeHandle`.

Required Coverage:
* At least one successful (i.e. called with correct arguments and assert on expected result, not applicable to `CreateWithNativeHandle` entry points)
* If this a query entry-point or one which accepts flags etc : we should tests every possible enumeration (where possible).
* A test case for each returned error code (exclude disaster situations i.e. OUT_OF_MEMORY etc)

**Comment by veselypeta** [comment]
This is likely blocked until the compilation pipeline is clarified

**Comment by veselypeta** [comment]
I think this can perhaps be closed as some kernel enqueue tests already exist @aarongreig ?

**Comment by aarongreig** [comment]
yeah this is done
