### ISSUE TITLE
Adds CTS tests for `urEnqueueMemImageFill` entry-point

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#236]
We should add conformance tests for `urEnqueueMemImageFill`.

Required Coverage:
* At least one successful (i.e. called with correct arguments and assert on expected result, not applicable to `CreateWithNativeHandle` entry points)
* If this a query entry-point or one which accepts flags etc : we should tests every possible enumeration (where possible).
* A test case for each returned error code (exclude disaster situations i.e. OUT_OF_MEMORY etc)

**Comment by veselypeta** [comment]
This entry-point is currently disabled in the UR spec.

**Comment by kbenzie** [comment]
Since its not currently in the spec, we don't need to implement CTS for it. Closing for now, can reopen if we add this to the spec.
