### ISSUE TITLE
 UR_RESULT_ERROR_UNSUPPORTED_FEATURE

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/unified-runtime#2401]
To reproduce the error on an Intel dGPU,

Go to https://github.com/zjin-lcf/HeCBench/tree/master/src/zmddft-sycl

make CC=icpx run
./main 100
terminate called after throwing an instance of 'sycl::_V1::exception'
  what():  Native API failed. Native API returns: 44 (UR_RESULT_ERROR_UNSUPPORTED_FEATURE)
make: *** [Makefile:77: run] Aborted

**Comment by kbenzie** [comment]
Please provide more information about the failure, including the logs output with the `SYCL_UR_TRACE=-1` environment variable set as documented [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#sycl_ur_trace-options).

**Comment by jinz2014** [comment]
---> urEnqueueDeviceGlobalVariableWrite(.hQueue = 0x2719250, .hProgram = 0x1bf3310, .name = 0x1bede10 (_Z2D3), .blockingWrite = 0, .count = 8, .offset = 0, .pSrc = 0x29dba80, .numEventsInWaitList = 0, .phEventWaitList = {}, .phEvent = 0x7ffe67b30568 (0x2a43770)) -> UR_RESULT_ERROR_UNSUPPORTED_FEATURE;
