### ISSUE TITLE
USM entry points should have optional `properties` argument.

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#258]
Currently the UR spec mandates that USM entry points with a properties argument like `urUSMDeviceAlloc` to have properties not be null. The intel OpenCL extension for USM allows this properties arguement to be null, when no additional properties are required [see here](https://registry.khronos.org/OpenCL/extensions/intel/cl_intel_unified_shared_memory.html#_host_allocations).

We could either make the properties parameter optional or since props are zero terminated, when no properties are required do something like the following.

```cpp
void *ptr = nullptr;
ur_usm_mem_flags_t props[] = {0};
urUSMDeviceAlloc(context, device, props, sizeof(int), &ptr);
```

**Comment by igchor** [comment]
I belive this should be resolved by: https://github.com/oneapi-src/unified-runtime/pull/264
I've replaced `ur_usm_mem_flags_t*` parameter by (optional) `ur_usm_desc_t*`.  Do you think this is OK?

**Comment by kbenzie** [comment]
#264 was merged so closing this issue.
