### ISSUE TITLE
Consider passing both host and device flags/descriptors to urUSMSharedAlloc

### ISSUE THREAD

**Issue by igchor** [oneapi-src/unified-runtime#266]
Currently we are passing a single flags/descriptor parameter to `urUSMSharedAlloc`:  
https://github.com/oneapi-src/unified-runtime/blob/61cb864b3a73918124bff11f9ad58dafb8c7769a/include/ur_api.h#L2814-L2821

LevelZero on accepts both host and device allocation descriptors:
https://github.com/oneapi-src/level-zero/blob/4ed13f327d3389285592edcf7598ec3cb2bc712e/include/ze_api.h#L4342-L4351

**Comment by jandres742** [comment]
shared allocations may migrate from host to device, so this way, we provide users with the possibility to influence behavior in both locations.
