### ISSUE TITLE
Update urProgramSetSpecializationConstant to follow PI changes for CUDA

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#269]
https://github.com/intel/llvm/pull/7946 introduces a change/additional version of the entry point to set specialization constants to enable better support for the feature in the CUDA plugin.

Track the changes made to the interface and update the UR specification to enable the same use case.

**Comment by jchlanda** [comment]
It might be beneficial to provide multiple ways of setting the specialization constants. At present we use the call to `piextProgramSetSpecializationConstant` in two distinct ways:
* set the value of a single spec constant at a given Id,
* copy entire blob of memory corresponding to all constants aggregated to a CUDA symbol.

Please see: https://github.com/intel/llvm/pull/7946#discussion_r1113190793 fo background discussion.

**Comment by kbenzie** [comment]
#306 is a proposal to drive discussion and help decide if that's the direction we want to pursue.
