### ISSUE TITLE
Consider adding support for USM memory capabilities

### ISSUE THREAD

**Issue by fabiomestre** [oneapi-src/unified-runtime#280]
### Issue

PI contains the following struct:

```
typedef enum : pi_bitfield {
  PI_USM_ACCESS = (1 << 0),
  PI_USM_ATOMIC_ACCESS = (1 << 1),
  PI_USM_CONCURRENT_ACCESS = (1 << 2),
  PI_USM_CONCURRENT_ATOMIC_ACCESS = (1 << 3)
} _pi_usm_capabilities;
```

It is used in the plugins but there doesn't seem to be any equivalent in Unified Runtime. 

### Task

Add support for usm memory capabilities.

In addition, urDeviceGetInfo() currently returns a boolean for:

> enumerator UR_DEVICE_INFO_USM_HOST_SUPPORT
> bool: support USM host memory access
> 
> enumerator UR_DEVICE_INFO_USM_DEVICE_SUPPORT
> bool: support USM device memory access
> 
> enumerator UR_DEVICE_INFO_USM_SINGLE_SHARED_SUPPORT
> bool: support USM single device shared memory access
> 
> enumerator UR_DEVICE_INFO_USM_CROSS_SHARED_SUPPORT
> bool: support USM cross device shared memory access
> 
> enumerator UR_DEVICE_INFO_USM_SYSTEM_SHARED_SUPPORT
> bool: support USM system wide shared memory access

If usm memory capabilities is added, those enums should be changed to return a bitfield of capabilities instead.

**Comment by bmyates** [comment]
Is there any update to this proposal? Are there any reasons not to add usm caps to UR?  If no objection, I can submit a PR for consideration. 

Currently, L0 adapter is returning a capability bitmask for UR_DEVICE_INFO_USM_*_SUPPORT rather than ur_bool_t as specified.

**Comment by kbenzie** [comment]
This came up again for us during the CUDA port, the bool/bitfield mapping isn't an annoying mismatch. PI and the OpenCL extension both use the bitfield, I'm not sure how this came to be a set of bool queries.

There's no blockers that I'm aware of so I think we should go ahead with this change to a bitfield. I will happily review a PR @bmyates but if something comes up please let me know and I can prioritize making this change.
