### ISSUE TITLE
Enable adapter specific testing

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#284]
As part of porting PI plugins to UR we also need to enable testing of adapter specific features. The most obvious of these is to test native handles to make sure integration and interop with the underlaying adapter interface is working as expected.

This is gated on adapter code moving into this repository.

* Determine where the adapter specific code should reside
* Document this in the readme
* Implement an example of what this should look like, either with the null adapter or when the first real adapter is moved into this repository.

**Comment by kbenzie** [comment]
As discussed [here](https://github.com/oneapi-src/unified-runtime/pull/680#discussion_r1251895193) more extensive testing of `urPlatformGetLastError` is an ideal candidate for adapter specific testing as this relies on knowledge of adapter implementation details in order to actually trigger an adapter specific error so that the message and error code returned from `urPlatformGetLastError` can be validated.

**Comment by veselypeta** [comment]
Completed as part of 
#790 & #763
