### ISSUE TITLE
Devices without local memory?

### ISSUE THREAD

**Issue by al42and** [oneapi-src/unified-runtime#316]
Hello! 

There is an issue about converting `enum` values in IntelLLVM, https://github.com/intel/llvm/issues/8389, that brings up the question: does UR have a concept of devices without local memory?

SYCL assumes that all CPUs and GPUs have local memory but allows for the existence of devices without one:

> Returns the type of local memory supported. This can be `info::local_mem_type::local` implying dedicated local memory storage such as SRAM, or `info::local_mem_type::global`. If this SYCL device is of type `info::device_type::custom` this can also be info::local_mem_type::none, indicating local memory is not supported.
> (https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_device_information_descriptors)

The "Objective" of UR suggests that it should support a lot of devices, although the chart below this quote seems to be more specific (and only target devices with some kind of local memory):

> The objective of the oneAPI Unified Runtime is to provide a unified interface to device agnostic runtimes such as DPC++ across a wide variety of software platforms.
> (https://oneapi-src.github.io/unified-runtime/core/INTRO.html#objective)

To determine how https://github.com/intel/llvm/issues/8389 should be best resolved, it is necessary to know whether UR wants to have `UR_DEVICE_LOCAL_MEM_TYPE_NONE` or not.

**Comment by kbenzie** [comment]
Hello @al42and, that's for reporting this. UR is here to enable higher level parallel language runtimes so this does look like an ommision which we should fix.
