### ISSUE TITLE
Extend urUSMGetMemAllocInfo to return memory pool handle?

### ISSUE THREAD

**Issue by igchor** [oneapi-src/unified-runtime#326]
It might be useful if someone wants to allocate memory from a pool that contains a specific pointer.

**Comment by kbenzie** [comment]
This makes sense to me, I think that would just mean adding `UR_USM_ALLOC_INFO_POOL` to [ur_usm_alloc_info_t](https://oneapi-src.github.io/unified-runtime/core/api.html#ur-usm-alloc-info-t) and adding it to the list of enums to test [here](https://github.com/oneapi-src/unified-runtime/blob/main/test/conformance/usm/urUSMGetMemAllocInfo.cpp#L9).
