### ISSUE TITLE
Allow optional null arguments in API generation

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#33]
Currently any pointer arguments to entry points in the API automatically have a error condition that the API should return `UR_RESULT_ERROR_INVALID_NULL_POINTER ` see [here](https://github.com/oneapi-src/unified-runtime/blob/main/scripts/parse_specs.py#L667).

Whilst this makes sense for most pointer parameters, some are optional e.g. return events. We should generalize this logic to allow for optional pointer arguments.

**Comment by kbenzie** [comment]
@jatinx is looking into this.

**Comment by FranklandJack** [comment]
I think this already exists. e.g. the `phEventWaitList` in [`urEnqueueKernelLaunch`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L536) is marked *optional* and there is no requirement that it is non-null.

**Comment by kbenzie** [comment]
@veselypeta since this seems to be supported in the generator, lets use this ticket to make all of the `phEvent` arguments optional if they are not alreayd.
