### ISSUE TITLE
Missing _ur_event_status enumeration 

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#35]
Unified Runtime is missing the enumeration of values for querying and setting event statuses.

[PI has the following](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/detail/pi.h#L122-L127) (which matches OpenCL):
```
typedef enum {
  PI_EVENT_COMPLETE = 0x0,
  PI_EVENT_RUNNING = 0x1,
  PI_EVENT_SUBMITTED = 0x2,
  PI_EVENT_QUEUED = 0x3
} _pi_event_status;
```

Unified Runtime already has the ability to query this property via `urEventGetInfo` with the `UR_EVENT_INFO_EVENT_INFO_COMMAND_EXECUTION_STATUS` query, so we should add an enumeration for the values the returned argument can be set to.

**Comment by FranklandJack** [comment]
The `pi_event_status` type has usage [here](https://github.com/intel/llvm/blob/1db0e81f7fa4e07aaf432156a9ae257b33f0a1e6/sycl/source/detail/event_impl.cpp#L406) so is a definite requirement.

**Comment by veselypeta** [comment]
Completed as part of #70
