### ISSUE TITLE
`ur_sampler_properties_t` enum should not start from 0

### ISSUE THREAD

**Issue by callumfare** [oneapi-src/unified-runtime#373]
The `ur_sampler_properties_t` enum has values starting from 0. This isn't compatible with `urSamplerCreate`, which takes a 0-terminated list of property/value pairs. `UR_SAMPLER_PROPERTIES_NORMALIZED_COORDS` is interpreted as the end of the list.

Similar types that don't have this issue are `ur_device_partition_t` which takes its values from PI instead, and `ur_queue_properties_t` which starts from -1.

**Comment by kbenzie** [comment]
The `pProps` should be turned into a pointer to struct containing the sampler enum creation flags.
