### ISSUE TITLE
Missing device queries

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#39]
The following list of device queries are present in PI and missing in Unified Runtime. If we are to have parity with PI we should consider whether we need to add these queries:

-    `PI_DEVICE_INFO_DEVICE_ID`
-    `PI_DEVICE_INFO_GPU_EU_COUNT_PER_SUBSLICE`
-    `PI_DEVICE_INFO_BUILD_ON_SUBDEVICE`
-    `PI_EXT_INTEL_DEVICE_INFO_FREE_MEMORY`
-    `PI_EXT_INTEL_DEVICE_INFO_MEMORY_CLOCK_RATE`
-    `PI_EXT_INTEL_DEVICE_INFO_MEMORY_BUS_WIDTH`
-    `PI_DEVICE_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES`
-    `PI_DEVICE_INFO_GPU_HW_THREADS_PER_EU`
-    `PI_DEVICE_INFO_BACKEND_VERSION`
-    `PI_EXT_ONEAPI_DEVICE_INFO_BFLOAT16`
-    `PI_EXT_ONEAPI_DEVICE_INFO_MAX_GLOBAL_WORK_GROUPS`
-    `PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_1D`
-    `PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_2D`
-    `PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_3D`
-    `PI_EXT_ONEAPI_DEVICE_INFO_CUDA_ASYNC_BARRIER`

**Comment by kbenzie** [comment]
#55 is technically the duplicate but has more info so closing this issue.
