### ISSUE TITLE
Update UR versions of piext*CreateWithNativeHandle entry points

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#392]
The `piext*CreateWithNativeHandle` entry points have an additional parameter `OwnNativeHandle` which is missing from UR versions of these entry points. Additionally in https://github.com/intel/llvm/pull/7196 a new `piextQueueGetNativeHandle2` introduces another parameter `int32_t nativeHandleDesc`.

Additionally, the `ur*CreateWithNativeHandle` entry points do not currently provide any form of extensibility which could require ABI changes or additional entry points to be introduced in future.

As such, update all `ur*CreateWithNativeHandle` entry points to include a pointer to struct parameter, which `pNext` chaining abilities, while also enabling the `OwnNativeHandle` and `nativeHandleDesc` functionality with is already present in PI.

**Comment by smaslov-intel** [comment]
Note that `ur*getNativeHandle` also need to return `nativeHandleDesc`

**Comment by jandres742** [comment]
So we need OwnNativeHandle in all the CreateNativeWithHandle APIs. Below you can see the interfaces I have identified currently need this change, and some extra ones:

urMemCreateWithNativeHandle: needs
    OwnNativeHandle

urKernelCreateWithNativeHandle: needs
    Program
    OwnNativeHandle
Draft PR: https://github.com/oneapi-src/unified-runtime/pull/434

urContextGetNativeHandle: needs
    NumDevices
    Devices
    OwnNativeHandle
Draft PR: https://github.com/oneapi-src/unified-runtime/pull/433

**Comment by kbenzie** [comment]
Okay, these look reasonable to me. I do think that the `bool OwnNativeHandle` should exist in `ur_<object>_native_handle_props_t` structs for all the `ur<Object>CreateWithNativeHandle` entry points to enable `pNext` chaining.

**Comment by jandres742** [comment]
> Okay, these look reasonable to me. I do think that the `bool OwnNativeHandle` should exist in `ur_<object>_native_handle_props_t` structs for all the `ur<Object>CreateWithNativeHandle` entry points to enable `pNext` chaining.

Thanks @kbenzie . Good idea. Please see https://github.com/oneapi-src/unified-runtime/pull/433.

**Comment by jandres742** [comment]
#433 merged for urContextGetNativeHandle.

https://github.com/oneapi-src/unified-runtime/pull/434 updated for urKernelCreateWithNativeHandle

**Comment by jandres742** [comment]
PR for urQueueCreateWithNativeHandle: https://github.com/oneapi-src/unified-runtime/pull/468

**Comment by jandres742** [comment]
PR for urEventCreateWithNativeHandle https://github.com/oneapi-src/unified-runtime/pull/474

**Comment by kbenzie** [comment]
I've done a review of the all the `CreateWithNativeHandle` entry points, these do not currently have `pProperties` parameters:

* urPlatformCreateWithNativeHandle
* urDeviceCreateWithNativeHandle
* urProgramCreateWithNativeHandle
* urSamplerCreateWithNativeHandle

I'm happy to take this over @jandres742 if you've done all of the entry points important to the L0 port done.

**Comment by jandres742** [comment]
@kbenzie : thanks! Yes, feel free please to complete these with the pProperties parameter.

**Comment by kbenzie** [comment]
#515 resolved the final entry point missing `pProperties`
