### ISSUE TITLE
Consider typedefing ur_bool

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#42]
Any boolean values passed to APIs in Unified Runtime are currently of `bool` type. In C `bool` has to be large enough to hold the `true` and `false` values, other than that there are no restrictions on its size.

Other compute frameworks like OpenCL typically define their own typedefs of the various integer types in C to avoid parameters to entry points having different sizes. For example, OpenCL defines a [`typdef cl_uint cl_bool`](https://github.com/KhronosGroup/OpenCL-Headers/blob/b590a6bfe034ea3a418b7b523e3490956bcb367a/CL/cl.h#L39) (where cl_uint is always 32 bits).

PI defines a [`pi_bool`](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/detail/pi.h#L105) type and the global values `PI_TRUE/PI_FALSE` for comparisons. A [`ur_bool_t`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L87) type has also been added to Unified Runtime (although it doesn't appear to be used in any entry points).

We should consider whether we want to replace `bool` usage with `ur_bool_t` in Unified Runtime and define some global `UR_TRUE/UR_FALSE` values.

Alternatively we could follow the Vulkan example of using the predefined platform independent C types defined in `stdint.h` and replace `bool` usage with a type of known width such as `int8_t` and specify non-zero values as *truthy*. 

This would also address the issues raise in: https://github.com/oneapi-src/unified-runtime/pull/3

**Comment by kbenzie** [comment]
This already exists [here](https://github.com/oneapi-src/unified-runtime/blob/main/scripts/core/common.yml#L55-L58).
