### ISSUE TITLE
Missing ur_mem_advice_t enum values

### ISSUE THREAD

**Issue by omarahmed1111** [oneapi-src/unified-runtime#423]
There is some enum values in `pi_mem_advice` that does not map to UR:
```
  PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY
  PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY
  PI_MEM_ADVICE_CUDA_SET_PREFERRED_LOCATION_HOST
  PI_MEM_ADVICE_CUDA_UNSET_PREFERRED_LOCATION_HOST
  PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY_HOST
  PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY_HOST
```
It is not clear how to map these with the existing `ur_mem_advice_t` enum values. Is there a compatibility between these enum pi values and the existing `ur_mem_advice_t` enum values? Maybe if there is not, we could add new enum values to `ur_mem_advice_t` to address those.

**Comment by kbenzie** [comment]
https://github.com/KhronosGroup/SYCL-Docs/pull/197 has documentation of these enumerations.

**Comment by igchor** [comment]
There's so direct mapping of those values to what we have in UR right now.

I initially thought that we already support `SET_PREFERRED_LOCATION_HOST` through host/device-specific descriptors but I realized that we only use that during allocation for `flags`, e.g.: https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L2373 not `hints`. 

Unless we expect  `ur_usm_advice_flags_t` to require some extra context/parameters in future I think we should just extend `ur_mem_advice_t` with those new 6 values.
