### ISSUE TITLE
Add entry-point to UR which matches `piPluginGetBackendOptions`

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#427]
In [intel/llvm/8763](https://github.com/intel/llvm/pull/8763) introduced a new entry-point to PI to enable the propagation of compile flags to the device backend compiler.

```cpp
__SYCL_EXPORT pi_result piPlatformGetBackendOption(pi_platform platform,
                                                   const char *frontend_option,
                                                   const char **backend_option);
```

We should add a compatible function to UR.

**Comment by kbenzie** [comment]
First draft of this was called `piPluginGetBackendOption` but UR didn't carry over the plugin entry point concept so should be a platform entry point instead.
