### ISSUE TITLE
Add entry-point to UR to support `piextMemImageCreateWithNativeHandle`.

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#428]
intel/llvm#8603 introduces `piextMemImageCreateNativeHandle`.

```cpp
__SYCL_EXPORT pi_result piextMemImageCreateWithNativeHandle(
    pi_native_handle nativeHandle, pi_context context, bool ownNativeHandle,
    const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc,
    pi_mem *img);
```

We should add this entry-point to UR, but this will likely depend on #392 being resolved.

**Comment by kbenzie** [comment]
@jandres742 these are included in https://github.com/intel/llvm/pull/8603, its not clear to me why though. Perhaps the author @againull can shed some light on why these are necessary?

**Comment by againull** [comment]
> @jandres742 these are included in [intel/llvm#8603](https://github.com/intel/llvm/pull/8603), its not clear to me why though. Perhaps the author @againull can shed some light on why these are necessary?

Hi @kbenzie, sorry, I just merged the PR. Author is @cperkinsintel. @cperkinsintel Could you please help with the questions above?

**Comment by cperkinsintel** [comment]
> why do we need const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc? Image format has been already defined when creating the original native handle, so we cannot change it anymore, right?

That is correct, it cannot be changed. But the information encapsulated in the ImageFormat and ImageDesc are needed by SYCL itself to set up the image on its side.  (Technially the SYCL facing side of this API takes `sycl::image_channel_order` and other `sycl::` namespace args, which are converted into PI format.  

The LevelZero API does not expose a function for retrieving this information from the native image handle, so it must be provided by the user.  It's not optimal, but it's the only path forward in the interim.

**Comment by jandres742** [comment]
thanks @cperkinsintel for the details.

**Comment by kbenzie** [comment]
I think the additional arguments necessary for native image handles can be addressed in UR with a creation properties struct for `urMemCreateWithNativeHandle` as discussed in #392.

**Comment by kbenzie** [comment]
> I think the additional arguments necessary for native image handles can be addressed in UR with a creation properties struct for `urMemCreateWithNativeHandle` as discussed in #392.

Decided against this approach, #461 now adds a separate entry point.
