### ISSUE TITLE
Handling Devices Duplicated via Multiple Adapters

### ISSUE THREAD

**Issue by alycm** [oneapi-src/unified-runtime#459]
If a single hardware device is supported by multiple adapters, e.g. a GPU supporting Level Zero and OpenCL, then it could be enumerated multiple times.

Should such duplicates be filtered out so that a hardware device is only presented once, but if so how to prioritise which adapter to expose?

Should such duplicates be left and let the language runtime about handle it using UUIDs?

**Comment by kbenzie** [comment]
Possibly related to `ONEAPI_DEVICE_SELECTOR` #220

**Comment by alycm** [comment]
WG call discussion: Unified runtime should report everything it sees, even if that means reporting one device more than more.  Higher levels handle it (or not).
