### ISSUE TITLE
Add a Contribution Guide to UR

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#490]
From the WG discussion we agreed that we should add a contribution guide to unified-runtime, which should outline

* How to add experimental features
* How third-parties can contribute

**Comment by kbenzie** [comment]
Partially addressed by #546.

**Comment by kbenzie** [comment]
#546 was later expanded to cover all of:

* core feature
* core optional feature
* experimental feature

and is applicable to any contributor.
