### ISSUE TITLE
Null native handles should be allowed

### ISSUE THREAD

**Issue by callumfare** [oneapi-src/unified-runtime#502]
Currently the spec mandates that entry points return `UR_RESULT_ERROR_INVALID_NULL_HANDLE` if given a native handle that is equal to `NULL`. However this can cause problems, as it is possible for a valid native handle to be 0. For example in CUDA, the `CUdevice` type is just `int`, and `0` is a valid value (and I believe generally the value of the first device on the system).

We should remove this check from the spec and update the CTS tests. We also might want to also change `ur_native_handle_t` to be `inttptr_t` to make this more explicit.

**Comment by jandres742** [comment]
could we have the native_handle_t be a pointer (intptr_t as suggested), and keep the mandate that it must be non-null? For CUDA, then we would have a pointer to an integer, which has the value of 0.

Removing the mandate that needs to be non-null looks weird. I mean, if it is null, then how is the object being created, if there's no native handle passed?

**Comment by kbenzie** [comment]
Would it not be a requirement to perform a heap allocation to store the CUDA native handle then? That also doesn't feel nice.

**Comment by kbenzie** [comment]
Fixed in #720
