### ISSUE TITLE
Redesign entry points taking in/out parameter

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#52]
# Issue
Some Unified Runtime entry points are taking in/out parameters as pointers and treating the argument as an in or out parameter depending on the value at the address held in the pointer. Whilst this approach does allow the spec to reduce the number of arguments passed to these APIs by one, the semantics is confusing especially when coming from PI and OpenCL where the equivalent APIs have dedicated out parameters. It is also error prone if the caller accidentally leaves the value uninitialized which could result in indeterminate behavior at runtime.

Note that this pattern seems to have been adopted inconsistently throughout the UR spec, some entry points use it and some use the PI/OpenCL style (see below)

# Example

[`urDeviceGet`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L2673) has the following documentation:
```
urDeviceGet(
    ur_platform_handle_t hPlatform,                 ///< [in] handle of the platform instance
    ur_device_type_t DevicesType,                   ///< [in] the type of the devices.
    uint32_t* pCount,                               ///< [in,out] pointer to the number of devices.
                                                    ///< If count is zero, then the call shall update the value with the total
                                                    ///< number of devices available.
                                                    ///< If count is greater than the number of devices available, then the
                                                    ///< call shall update the value with the correct number of devices available.
    ur_device_handle_t* phDevices                   ///< [out][optional][range(0, *pCount)] array of handle of devices.
                                                    ///< If count is less than the number of devices available, then platform
                                                    ///< shall only retrieve that number of devices.
    );
```
where the `pCount` is treated as an out parameter if the value at that address is zero and otherwise is the size of the value the array that will be passed via `phDevices` parameter.

Compare this to the [`piDevicesGet`](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/detail/pi.h#L989) entry point:
```
__SYCL_EXPORT pi_result piDevicesGet(pi_platform platform,
                                     pi_device_type device_type,
                                     pi_uint32 num_entries, pi_device *devices,
                                     pi_uint32 *num_devices);
```
This has dedicated `num_entries` representing the size of the array passed in `devices` and a `num_devices` parameter which will return the number of devices in the platform of type `device_type` to the caller.

This is also the style used in OpenCL with [`clGetDeviceIDs`](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clGetDeviceIDs):
```
cl_int clGetDeviceIDs(
    cl_platform_id platform,
    cl_device_type device_type,
    cl_uint num_entries,
    cl_device_id* devices,
    cl_uint* num_devices);

```

Other APIs such as [`urPlatformGetInfo`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3696) unconditionally treat parameters as in/out updating the value at the address passed after first reading it:
```
UR_APIEXPORT ur_result_t UR_APICALL
urPlatformGetInfo(
    ur_platform_handle_t hPlatform,                 ///< [in] handle of the platform
    ur_platform_info_t PlatformInfoType,            ///< [in] type of the info to retrieve
    size_t* pSize,                                  ///< [in,out] pointer to the number of bytes needed to return info queried.
                                                    ///< the call shall update it with the real number of bytes needed to
                                                    ///< return the info
    void* pPlatformInfo                             ///< [out][optional] array of bytes holding the info.
                                                    ///< if *pSize is not equal to the real number of bytes needed to return
                                                    ///< the info then the ::UR_RESULT_ERROR_INVALID_SIZE error is returned and
                                                    ///< pPlatformInfo is not used.
    );
```
In this case the value at `pSize` is unconditionally updated by the entry point however its value as an in parameter is only used in the case that `pPlatformInfo` is non-null.

# Task 

Replace the in/out parameters with dedicated in and out parameters for the following entry points:
* [`urPlatformGet`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3645)
* [`urPlatformGetInfo`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3696)
* [`urDeviceGet`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L2673)
* [`urDeviceGetInfo`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L2822)
* [`urDevicePartition`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L2931)
* [`urProgramGetInfo`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3980)
* [`urKernelGetInfo`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3219)
* [`urKernelGetGroupInfo`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3250)
* [`urKernelGetSubGroupInfo`](https://github.com/oneapi-src/unified-runtime/blob/main/include/ur_api.h#L3273)

**Comment by veselypeta** [comment]
I also found
*urContextGetInfo*
Had the same problem
