### ISSUE TITLE
piclProgramCreateWithSource has no equivalent in UR

### ISSUE THREAD

**Issue by fabiomestre** [oneapi-src/unified-runtime#540]
Currently, UR does not have an entrypoint that is equivalent to piclProgramCreateWithSource. This seems to have been a deliberate decision given this implementation in pi2ur:
```

inline pi_result piclProgramCreateWithSource(pi_context Context,
                                             pi_uint32 Count,
                                             const char **Strings,
                                             const size_t *Lengths,
                                             pi_program *RetProgram) {
  std::ignore = Context;
  std::ignore = Count;
  std::ignore = Strings;
  std::ignore = Lengths;
  std::ignore = RetProgram;
  die("piclProgramCreateWithSource: not supported in UR\n");
  return PI_ERROR_INVALID_OPERATION;
}
```

However, to finish the port of the OpenCL plugin to UR, this function has to be handled. For now, an OpenCL specific implementation has been added to pi2ur. However, there is 2 options in the long term:

- Handle the implementation of this function directly in SYCL RT by using UR/PI native handles.
- Create a urProgramCreateWithSource() entrypoint.

Currently Sycl only supports compiling kernels from source with OpenCL backends. However, I wonder if in the future this functionality might be extended to support similar features in HIP and/or CUDA. If that's the case, it might make sense to create the urProgramCreateWithSource entrypoint.

**Comment by kbenzie** [comment]
https://github.com/intel/llvm/pull/9899 has been merged, closing as won't do.
