### ISSUE TITLE
Invalid use of "std::filesystem"

### ISSUE THREAD

**Issue by smaslov-intel** [oneapi-src/unified-runtime#547]
This should be just "filesystem" not "std::filesystem":

https://github.com/oneapi-src/unified-runtime/blob/a6083f5c535ada2127109a5aedbdb4b033302e4b/source/common/logger/ur_sinks.hpp#L172

Also testing with gcc 4.7.5 is needed, as it is used by some of dependecies

**Comment by smaslov-intel** [comment]
@pbalcer : will you add testing with older gcc?

**Comment by kbenzie** [comment]
intel/llvm is now requiring C++17 and UR follows this requirement. GCC 4.7.5 definitely does not support C++17 so I'm not sure how intel/llvm could be getting compiled with it.

In the first RHEL 7 bug report we got, the compiler toolchain in use was GCC 7.x even though the default toolchain in that distro is GCC 4.7.5. So it feels to me like that is the actual minimum bar for GCC toolchain support.
