### ISSUE TITLE
Missing device info enumeration values

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#55]
The [`_pi_device_info`](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/detail/pi.h#L301) enumeration in PI has the following enumeration values which do not have equivalents in Unified Runtime:
- `PI_DEVICE_INFO_DEVICE_ID` - [used here](https://github.com/intel/llvm/blob/4f7787c8d12df6bfb8381b412bbc187d0b6aca40/sycl/source/detail/device_impl.cpp#L321)
- `PI_DEVICE_INFO_GPU_EU_COUNT_PER_SUBSLICE` - [used here](https://github.com/intel/llvm/blob/4f7787c8d12df6bfb8381b412bbc187d0b6aca40/sycl/source/detail/device_impl.cpp#L345)
- `PI_DEVICE_INFO_BUILD_ON_SUBDEVICE` - [used here](https://github.com/intel/llvm/blob/fc136d69eab778ed670d751b49547e0930ef007b/sycl/source/detail/program_manager/program_manager.cpp#L544)
- `PI_EXT_INTEL_DEVICE_INFO_FREE_MEMORY` - [used here](https://github.com/intel/llvm/blob/4f7787c8d12df6bfb8381b412bbc187d0b6aca40/sycl/source/detail/device_impl.cpp#L353)
- `PI_EXT_INTEL_DEVICE_INFO_MEMORY_CLOCK_RATE` - [used here](https://github.com/intel/llvm/blob/4f7787c8d12df6bfb8381b412bbc187d0b6aca40/sycl/source/detail/device_impl.cpp#L357)
- `PI_EXT_INTEL_DEVICE_INFO_MEMORY_BUS_WIDTH` - [used here](https://github.com/intel/llvm/blob/4f7787c8d12df6bfb8381b412bbc187d0b6aca40/sycl/source/detail/device_impl.cpp#L361)
- `PI_DEVICE_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES` - [used here](https://github.com/intel/llvm/blob/1fa1416b644876c24a2c56f2f9981f3bac9497ae/sycl/include/sycl/info/device_traits.def#L117)
- `PI_DEVICE_INFO_GPU_HW_THREADS_PER_EU` - [used here](https://github.com/intel/llvm/blob/4f7787c8d12df6bfb8381b412bbc187d0b6aca40/sycl/source/detail/device_impl.cpp#L349)
- `PI_DEVICE_INFO_BACKEND_VERSION` - [used here](https://github.com/intel/llvm/blob/1fa1416b644876c24a2c56f2f9981f3bac9497ae/sycl/include/sycl/info/device_traits.def#L145)
- `PI_EXT_ONEAPI_DEVICE_INFO_BFLOAT16` - [used here](https://github.com/intel/llvm/blob/1fa1416b644876c24a2c56f2f9981f3bac9497ae/sycl/include/sycl/info/device_traits.def#L199)
- `PI_EXT_ONEAPI_DEVICE_INFO_MAX_GLOBAL_WORK_GROUPS` - [used here](https://github.com/intel/llvm/blob/0f4a0f3ba9d8d675e1dd2dd5119a679dc04919e2/sycl/include/sycl/info/ext_oneapi_device_traits.def#L5)
- `PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_1D` - [used here](https://github.com/intel/llvm/blob/0f4a0f3ba9d8d675e1dd2dd5119a679dc04919e2/sycl/include/sycl/info/ext_oneapi_device_traits.def#L6)
- `PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_2D` - [use here](https://github.com/intel/llvm/blob/0f4a0f3ba9d8d675e1dd2dd5119a679dc04919e2/sycl/include/sycl/info/ext_oneapi_device_traits.def#L7)
- `PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_3D` - [used here](https://github.com/intel/llvm/blob/0f4a0f3ba9d8d675e1dd2dd5119a679dc04919e2/sycl/include/sycl/info/ext_oneapi_device_traits.def#L8)
- `PI_EXT_ONEAPI_DEVICE_INFO_CUDA_ASYNC_BARRIER` - [used here](https://github.com/intel/llvm/blob/4f7787c8d12df6bfb8381b412bbc187d0b6aca40/sycl/source/detail/device_impl.cpp#L388)

We should add these to the UR spec.

**Comment by veselypeta** [comment]
#48
