### ISSUE TITLE
Change ur_bool_t to uint32_t

### ISSUE THREAD

**Issue by jandres742** [oneapi-src/unified-runtime#555]
pi_bool on sycl is uint32_t, so better to match it. We have seen already errors where due to the difference in size, a false value returned by the adapter is interpreted as true by the sycl runtime.

**Comment by kbenzie** [comment]
https://github.com/intel/llvm/pull/9672 was merged and the follow up will be to look into making `pi_bool` match `ur_bool_t` instead.
