### ISSUE TITLE
Clarify urKernelSetArgPointer spec

### ISSUE THREAD

**Issue by aarongreig** [oneapi-src/unified-runtime#558]
We have the urKernelSetArgPointer entry point to pass USM allocations as parameters to kernels. To get an idea of how this is set up we have these function signatures for some of the relevant entry points:
```
ur_result_t urUSMDeviceAlloc(ur_context_handle_t hContext, ur_device_handle_t hDevice,
                             const ur_usm_desc_t *pUSMDesc, ur_usm_pool_handle_t pool,
                             size_t size, void **ppMem)

ur_result_t urKernelSetArgPointer(ur_kernel_handle_t hKernel, uint32_t argIndex,
                                  const void *pArgValue)
```
Based on this, and the spec description for `urKernelSetArgPointer`'s `pArgValue` parameter
> [in][optional] USM pointer to memory location holding the argument value. If null then argument value is considered null.

Correct usage could look like this
```
void* allocation = nullptr;
size_t allocation_size = 32;

urUSMDeviceAlloc(context, device, nullptr, nullptr,
                 allocation_size, &allocation);

urKernelSetArgPointer(kernel, 0, allocation);
```
or this
```
void* allocation = nullptr;
size_t allocation_size = 32;

urUSMDeviceAlloc(context, device, nullptr, nullptr,
                 allocation_size, &allocation);

urKernelSetArgPointer(kernel, 0, &allocation);
```
depending on whether you put emphasis on
> [in][optional] **USM pointer** to memory location holding the argument value. If null then argument value is considered null.

or
> [in][optional] USM **pointer to memory location holding the argument** value. If null then argument value is considered null.

While implementing tests that make direct use of these entry points I've found that existing implementations expect the latter usage, and by extension this is also how the sycl runtime makes use of the analogous PI entry point.

This could do with some clarification. The wording can be changed to be more explicit, and to better match how USM pointers are passed around elsewhere it might make sense to change the function signature to this
```
ur_result_t urKernelSetArgPointer(ur_kernel_handle_t hKernel, uint32_t argIndex,
                                  void **pArgValue)
```

I would also suggest that how this is currently expected to work is... weird. Because of how the allocation entry points work, and how passing USM pointers to any other entry point works (see `urEnqueueUSMMemcpy` etc.), I found this behaviour pretty surprising. It would take some refactor work across all the UR adapters and unported plugins as well as the sycl runtime itself, but I think it's worth considering whether we should make the former usage in the above examples the expected behaviour, in the interest of making the library more intuitive.

**Comment by jandres742** [comment]
so the correct usage should be:

urKernelSetArgPointer(kernel, 0, &allocation);

since what we pass here is a pointer to an argument. For USM, that argument is a pointer (resulting in a pointer to a pointer), but for scalar variables, that is a pointer to a variable.

So if we are saying we want to be more explicit in the documentation, then I agree, we need to.

If we are saying instead we want to change the interface, then I dont  see the advantages and only problems. If we make now the argument to be just the USM pointer for USM allocations, the adapters (or drivers) would have now to add logic to know whether this is a pointer to a variable or a USM pointer, which means, adding additional logic where the the adapter or driver does a search on all currently active USM allocations to know if the pointer corresponds to one of them, and if not, then it knows the pointer is a pointer to a scalar variable, not to a USM pointer.

So, could you clarify what we want to change here?

**Comment by jandres742** [comment]
thanks @aarongreig . So we want to change the signature to:

>The wording can be changed to be more explicit, and to better match how USM pointers are passed around elsewhere it might make sense to change the function signature to this
>
>ur_result_t urKernelSetArgPointer(ur_kernel_handle_t hKernel, uint32_t argIndex,
                                  void **pArgValue)

if so, then I agree, it is better

**Comment by aarongreig** [comment]
That was my initial proposal to clarify the current behaviour, but there was agreement on the call that the current behaviour is likely a bug. So now the proposal is to keep the current signature and patch existing adapters (as well as pi2ur) to accept the correct level of indirection.

**Comment by jandres742** [comment]
> That was my initial proposal to clarify the current behaviour, but there was agreement on the call that the current behaviour is likely a bug. So now the proposal is to keep the current signature and patch existing adapters (as well as pi2ur) to accept the correct level of indirection.

if this needs to be handled in the adapters, then I think we are already doing it, as the adapters take care internally of getting the correct pointer. If there's something missing there or extra to do, we could add it, but I think we are good.

**Comment by aarongreig** [comment]
this is addressed in https://github.com/oneapi-src/unified-runtime/pull/805
