### ISSUE TITLE
[ur] Automatically generate `ur_structure_type_t`

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#563]
Following on from discussion about #546 and how to make it easier for external parties to make contributions it was noted that it should be possible to completed automate making changes to the `ur_structure_type_t` enumeration in a similar way that the `ur_function_t` enumeration is automatically generated for XPTI integration.

**Comment by veselypeta** [comment]
I've been looking into this for a bit and this actually might be quite a hard problem to solve for a couple of reasons:

* The `ur_structure_type_t` can only be generated after all types have been parsed - i.e. all extended structs have been identified.
* The `meta` data-structure is generated on-the-fly with each new type parsed and parsing of extended structs rely on `ur_structure_type_t` to already be parsed and available in `meta`

One other option which occurred to me is that we generate this similarly to how the registry is handled - by automatically updating it in it's own yaml file.

**Comment by kbenzie** [comment]
> One other option which occurred to me is that we generate this similarly to how the registry is handled - by automatically updating it in it's own yaml file.

Moving this into the registry is how I envisioned this working since its already automatically generated, would be better to avoid having multiple generated yaml files since this one already confuses people enough.

**Comment by veselypeta** [comment]
Closed with #670
