### ISSUE TITLE
SYCL RT request: need an API to provide memory access hint to urKernelSetArgMemObj

### ISSUE THREAD

**Issue by KseniyaTikhomirova** [oneapi-src/unified-runtime#572]
Backends could use memory access hint for low level optimizations (read access) although now we do not have any way to specify it.
I would like to propose addition of new parameter for memory object properties (in a way how urQueueCreate is done) to urKernelSetArgMemObj function.
I prepared PR to UR with proposal:
https://github.com/oneapi-src/unified-runtime/pull/571

Could you please review the proposal? Could the new API (the one you agree with) be included to the nearest release to enable this feature in SYCL RT too?

Short description of change:
_typedef struct ur_mem_obj_properties_t {
    ur_structure_type_t stype;
    void *pNext; 
    ur_mem_flags_t memory_access; 
} ur_mem_obj_properties_t;_

_urKernelSetArgMemObj(
    ur_kernel_handle_t hKernel,
    uint32_t argIndex, 
    ur_mem_handle_t hArgValue,
    **const ur_mem_obj_properties_t* pProperties**
);_

**Comment by kbenzie** [comment]
I'm confused by this proposal, access qualifiers are already specified during [urMemBufferCreate](https://oneapi-src.github.io/unified-runtime/core/api.html#urmembuffercreate) so I'm unsure why they would need to be specified again, with potentially different values, when calling [urKernelSetArgMemObj](https://oneapi-src.github.io/unified-runtime/core/api.html#urkernelsetargmemobj). I'd instead expect the Level Zero adapter to store the `flags` specified at creation, then use them when invoking a kernel execution.

**Comment by KseniyaTikhomirova** [comment]
@kbenzie the usage is different here, I mean that we could have the situation when we create buffer with read_write access but in exact kernel we create accessor (SYCL) for read only access. backend could optimize simultaneous read only accesses in this case. 
So we want to distinguish creation memory access flags and exact access mode required for every kernel.

**Comment by kbenzie** [comment]
Okay, are there relevant changes over in [intel/llvm](https://github.com/intel/llvm) you could link to for more context?

**Comment by KseniyaTikhomirova** [comment]
@kbenzie I have initial proposal for SYCL RT & plugins here https://github.com/intel/llvm/pull/9752/files#diff-b2a87c568d1ca4aea6c09ca3e3367ca1565e48b38ec611259b8d5e4b9215114cL683. Pointing to the line where we previously set read_write access for all cases.

**Comment by kbenzie** [comment]
Looks like `read_write` was hard-coded before rather than coming from the flags specified in `urMemBufferCreate` so it could be possible that this information is specified by the SYCL RT but is not being utilized in the Level Zero adapter?

That's only a possibility of course, just trying to explore all possibilities before actually committing to making changes to the UR interface which may not end up being necessary.

**Comment by KseniyaTikhomirova** [comment]
> Looks like `read_write` was hard-coded before rather than coming from the flags specified in `urMemBufferCreate` so it could be possible that this information is specified by the SYCL RT but is not being utilized in the Level Zero adapter?
> 
> That's only a possibility of course, just trying to explore all possibilities before actually committing to making changes to the UR interface which may not end up being necessary.

@kbenzie SYCL RT knows the information about usage but haven't passed it to plugins yet. It is the goal of my changes in SYCL and my proposal to UR: to introduce interface to pass this information to plugins/UR in order to L0 adapter could use it and eliminate hardcoded value there.

**Comment by kbenzie** [comment]
Understood, my question: Does the SYCL RT know this information earlier on when creates the buffer objects or does it only become available later on when it sets the kernel arguments?

**Comment by KseniyaTikhomirova** [comment]
> Understood, my question: Does the SYCL RT know this information earlier on when creates the buffer objects or does it only become available later on when it sets the kernel arguments?

No, this information is given at different points of time. Let me to describe an example. We create buffer with read-write access mode. Then we have command group with kernel that write something to this buffer and we want to set argument with write_only access (stage 1). After that we have the next command group with kernel that read the results written to the buffer on stage 1. In this case we want to set argument with read only access mode.
To conclude - RT got this information after buffer creation and could not pass it earlier.

**Comment by kbenzie** [comment]
Yes, I see. Thanks for the explanation.

**Comment by kbenzie** [comment]
Would you be open to the idea of a separate entry point?

```cpp
ur_result_t urMemSetAccessMode(
    ur_mem_handle_t hMem,
    ur_mem_flags_t flags
);
```

**Comment by KseniyaTikhomirova** [comment]
> Would you be open to the idea of a separate entry point?
> 
> ```c++
> ur_result_t urMemSetAccessMode(
>     ur_mem_handle_t hMem,
>     ur_mem_flags_t flags
> );
> ```

This information is needed to be attached to exact kernel submission. So it is valid for exact mem object used in exact kernel submission. Not sure how separate entry point fits into this.

**Comment by kbenzie** [comment]
Right, a new entry point would imply persistent state rather than transient state.

Is this also applicable to USM allocations?

**Comment by kbenzie** [comment]
> Could you please share more details about new entry point? This property is intended to be optional and attached to exact kernel. How are we supposed to use it? I

I'm not tied to this idea but it would go something like this:

* create a buffer with read-write (`urMemBufferCreate`) and store the access-mode in the buffer object
* decide to invoke a kernel:
  * call `urMemSetAccessMode` to read-only, change the access-mode state in the buffer object
  * call `urKernelSetMemObj` with the buffer object only
* kernel is launched `urEnqueueKernelLaunch` the buffer object keeps the access-mode previously set by `urMemSetAccessMode`

As for the multi-threading, all entry-points in UR must have thread safe implementations, likely via an internal lock, if multipl threads did decide to call `urMemSetAccessMode` at the same time if *could* mean you get an unexpected value in your `urEnqueueKernelLaunch`.

So I don't think this is viable for your use case.

**Comment by KseniyaTikhomirova** [comment]
@kbenzie I think we could introduce urMemSetAccessMode but it should have kernel as parameter as well (the same memory object could be used in different kernels with different access modes).
The only concern that is left that I see the trend in UR API to make it extendable while urMemSetAccessMode is very specific and will not allow to extend mem obj properties later (if anything will be needed).

**Comment by kbenzie** [comment]
> @kbenzie I think we could introduce urMemSetAccessMode but it should have kernel as parameter as well (the same memory object could be used in different kernels with different access modes).

Very doable.

> Am I right that you are concerned about original method extension because it breaks ABI?

Partially, we have a number of rather large in-flight PR's (my team are porting the CUDA, HIP, and OpenCL plugins over to UR) which are likely could affect but we have not yet committed to a stable ABI. My other concearn was to do with making `urKernelSetArgMemObject` inconsistent with the other `urKernelSetArg*` entry points.

> The only concern that is left that I see the trend in UR API to make it extendable while urMemSetAccessMode is very specific and will not allow to extend mem obj properties later (if anything will be needed).

Extensibility is definitely desirable.

I was discussing with a colleague yesterday about an issue in the HIP adapter which may need addition per-kernel-launch state in `urKernelSetArgPointer`.

We've also had a request to be able to set *all* kernel arguments with a single entry-points but we've been holding off on doing the design work for this during the transitionary phase will be port PI plugins to UR.

I see the following options:

1. Make `urKernelSetArgMemObj` extensible - original proposal
2. Leave `urKernelSetArg*` as is, and add `urMemSetAccessMode` - my initial idea
3. Make all `urKernelSetArg*` entry-points extensible - a more general solution
4. Start work on a new API to set all kernel args in one entry point - an involved design process that may take a lot of time

Option 3. feels like the sweet spot to me at the moment. What are your thoughts @KseniyaTikhomirova ?

**Comment by KseniyaTikhomirova** [comment]
@kbenzie Agree, the third point sounds better in the context of discussion. Although not fully got what is the difference between 1 and 3 option in context of my request. Are you suggesting that I should make the rest of the changes for other APIs?

**Comment by kbenzie** [comment]
> Are you suggesting that I should make the rest of the changes for other APIs?

That's one option.

Another would be to go ahead with your proposal, then we can follow up with the remaining changes, practically this probably makes most sense.

**Comment by KseniyaTikhomirova** [comment]
Ok, will fix your comments to my proposal today, thank you.

**Comment by KseniyaTikhomirova** [comment]
PR https://github.com/oneapi-src/unified-runtime/pull/571 is updated

**Comment by kbenzie** [comment]
With #571 merged, the remaining work for this issue is to also make [urKernelSetArgPointer](https://oneapi-src.github.io/unified-runtime/core/api.html#urkernelsetargpointer), [urKernelSetExecInfo](https://oneapi-src.github.io/unified-runtime/core/api.html#urkernelsetexecinfo), and [urKernelSetArgSampler](https://oneapi-src.github.io/unified-runtime/core/api.html#urkernelsetargsampler) extensible following the same pattern.
