### ISSUE TITLE
Decide if urEventSetStatus entry point is required

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#58]
# Issue 
PI supports a [`piEventSetStatus`](https://github.com/intel/llvm/blob/4f7787c8d12df6bfb8381b412bbc187d0b6aca40/sycl/include/sycl/detail/pi.h#L1437) entry point. This entry point doesn't seem to have any uses in the DPC++ runtime and would only really be of value if we intend to support user events which is something we've previously discussed not including in the Unified Runtime spec due to the burdensome device <-> host synchronization requirement they place on an adapter.

# Task
Decide if the a `urEventSetStatus` entry point is required in the Unified Runtime spec. If it is then add it, if it is not then no action is required.

**Comment by kbenzie** [comment]
#100 removed user event creation which is the only application for setting event status, as such this is not required.
