### ISSUE TITLE
Enum descriptions not properly rendering

### ISSUE THREAD

**Issue by isaacault** [oneapi-src/unified-runtime#597]
The descriptions for enum values don't seem to be rendering properly in the HTML. An example is [ur_device_info_t::UR_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES](https://oneapi-src.github.io/unified-runtime/core/api.html#_CPPv4N16ur_device_info_t46UR_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIESE). Notice how the description needs to be read from the bottom up. 

This seems to happen on some longer descriptions, but not all, as seen on [ur_device_info_t::UR_DEVICE_INFO_MAX_COMPUTE_QUEUE_INDICES](https://oneapi-src.github.io/unified-runtime/core/api.html#_CPPv4N16ur_device_info_t40UR_DEVICE_INFO_MAX_COMPUTE_QUEUE_INDICESE).

**Comment by veselypeta** [comment]
I've looked into this a little and my current working theory is that this is caused because the API documentation is parsed from the `ur_api.h` header before it has been formatted by clang-format. We should try and format the spec file before generating the docs and see if this fixes the problem.

**Comment by veselypeta** [comment]
Before:
![image](https://github.com/oneapi-src/unified-runtime/assets/22935437/f46d0bed-b048-449c-8e22-e2b6142ef352)
After:
![image](https://github.com/oneapi-src/unified-runtime/assets/22935437/ffc792fb-38b6-42b0-9c7d-d11e7e7f03cb)
