### ISSUE TITLE
Decide if piEnqueueNativeKernel entry point is required

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#60]
# Issue 
PI supports a [`piEnqueueNativeKernel`](https://github.com/intel/llvm/blob/4f7787c8d12df6bfb8381b412bbc187d0b6aca40/sycl/include/sycl/detail/pi.h#L1489) entry point. This entry point [doesn't seem to have any uses](https://github.com/intel/llvm/search?q=piEnqueueNativeKernel) in the DPC++ runtime so its value is questionable from the perspective of implementing SYCL however it may be of use to other language runtimes.

# Task
Decide if the a `urEnqueueNativeKernel` entry point is required in the Unified Runtime spec. If it is then add it, if it is not then no action is required.

**Comment by kbenzie** [comment]
Given there is no current usage of this entry point I don't see a need to add it at this time. If users find this useful moving forwards we can reevaluate. Closing this for now.
