### ISSUE TITLE
Entry points should not use `size_t` parameters.

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#61]
Currently the UR spec uses a mix of `size_t` and `uint32_t` params.

For example `urDevicePartition` uses `uint32_t` https://spec.oneapi.io/unified-runtime/latest/core/api.html#zerdevicegetinfo.
while, `urDeviceInfo` uses `size_t` https://github.com/oneapi-src/unified-runtime/blob/main/scripts/core/device.yml#L280

We should make make these all `uint32_t` as `size_t` is platform dependent.

**Comment by kbenzie** [comment]
I don't think I agree with this. Why do you want to get rid of `size_t`?
