### ISSUE TITLE
Add urMemImageGetInfo entry point

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#63]
# Issue

PI supports a [`piMemImageGetInfo`](https://github.com/intel/llvm/blob/4f7787c8d12df6bfb8381b412bbc187d0b6aca40/sycl/include/sycl/detail/pi.h#L1168) entry point which [has usage](https://github.com/intel/llvm/search?q=piMemImageGetInfo) in the DPC++ runtime.

Unified Runtime currently doesn't have a `urMemImageGetInfo` entry point.

# Task

Add a `urMemImageGetInfo` entry point to the Unified Runtime spec.

**Comment by veselypeta** [comment]
Depends on #56 Completed first
