### ISSUE TITLE
Add adapter specific return codes to platform/device GetInfo queries

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#636]
See discussion [here](https://github.com/oneapi-src/unified-runtime/pull/631#discussion_r1233863294) to explain why we should add these checks.

**Comment by JackAKirk** [comment]
I think these should be added to all UR functions that can call a native api, not just these get info ones.

**Comment by kbenzie** [comment]
> I think these should be added to all UR functions that can call a native api, not just these get info ones.

yes, that makes a lot of sense

**Comment by veselypeta** [comment]
We could potentially have the spec generator automatically add ADAPTER_SPECIFIC to every entry-point

**Comment by JackAKirk** [comment]
> We could potentially have the spec generator automatically add ADAPTER_SPECIFIC to every entry-point

Could make sense. Although I'm not 100% that every UR function will call a native API? Although it would seem strange if a UR function doesn't call a native API perhaps so maybe they all do.

**Comment by JackAKirk** [comment]
I think one exception to APIs that don't return `ADAPTER_SPECIFIC...` is `piPluginGetLastError` which actually returns the native message (and I think now @kbenzie is making it return the native code too). Maybe this is the only one though.

**Comment by veselypeta** [comment]
I mean isn't this all adapter specific. Any adapter could implement any entry-point to potentially call a native API.

**Comment by JackAKirk** [comment]
> I mean isn't this all adapter specific. Any adapter could implement any entry-point to potentially call a native API.

Yeah you're probably right. There are some where it seems unlikely a native api will be called by any plugin but I don't see the harm in just documenting the possibility universally regardless, especially since I think the majority are likely to call a native API in at least some adapters. I'm inclined to agree with your suggestion to just add it to every function documentation.
