### ISSUE TITLE
UR_LOG_VALIDATION seems to be unimplemented

### ISSUE THREAD

**Issue by aarongreig** [oneapi-src/unified-runtime#692]
I can't find any references to this environment variable outside the [documentation](https://github.com/oneapi-src/unified-runtime/blob/main/scripts/core/INTRO.rst?plain=1#L250) for it and some [tests](https://github.com/oneapi-src/unified-runtime/blob/main/test/layers/validation/CMakeLists.txt#L27) that don't appear to actually rely on it. We should implement it or remove it.

**Comment by pbalcer** [comment]
We shouldn't be adding test-only env variables to the docs anyway. This type of documentation reside in some README.md file for the directory where it's relevant (so probably `test/`).
So I think we should just remove it.

**Comment by kswiecicki** [comment]
> We shouldn't be adding test-only env variables to the docs anyway. This type of documentation should reside in some README.md file for the directory where it's relevant (so probably `test/`). So I think we should just remove it.

The validation layer logs information about invalid references made/retained throughout a program's lifetime. Is this functionality only meant to be used in tests? Or is the env variable too much and the validation layer should always log to `stdout`?

**Comment by pbalcer** [comment]
> > We shouldn't be adding test-only env variables to the docs anyway. This type of documentation should reside in some README.md file for the directory where it's relevant (so probably `test/`). So I think we should just remove it.
> 
> The validation layer logs information about invalid references made/retained throughout a program's lifetime. Is this functionality only meant to be used in tests? Or is the env variable too much and the validation layer should always log to `stdout`?

Ok, I misunderstood. You are right. Ignore what I wrote :)
