### ISSUE TITLE
Missing context info enum values 

### ISSUE THREAD

**Issue by jatinx** [oneapi-src/unified-runtime#75]
- PI_CONTEXT_INFO_PLATFORM - Its a useful information, used by some backend to make certain decision (device->platform->name). But this can also be done by urDeviceGetInfo(UR_DEVICE_INFO_PLATFORM)->urGetPlatformInfo(PLATFORM_NAME). So we can skip this.
- PI_CONTEXT_INFO_PROPERTIES - Cant find its usage
- PI_CONTEXT_INFO_REFERENCE_COUNT  Cant find its usage too. UR has the concept of context acquire/release, but no way to query its reference count. Its inconsistent, for device which also has acq/rel, we have a UR_DEVICE_INFO_REFERENCE_COUNT. can add it to make it consistent.
- PI_CONTEXT_INFO_ATOMIC_MEMORY_[ORDER|SCOPE]_CAPABILITIES - used to populate sycl device info for order/scope capabilities, Should they be moved to device info instead of context?

**Comment by callumfare** [comment]
We still seem to be missing `PI_CONTEXT_INFO_ATOMIC_MEMORY_[ORDER|SCOPE]_CAPABILITIES` which are needed for compatibility with PI
