### ISSUE TITLE
Restructure Directory Hierarchy

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#76]
# Issues
Following discussions on https://github.com/oneapi-src/unified-runtime/issues/22 it has been decided that this repository will act as a monorepo for the various components of Unified Runtime: headers, spec, loader, utilities adapters, tests etc.

Since this repo currently only contains the spec and headers it will need to be logically restructured to host the other components in a sensible way. 

# Task

1. Design and agree on a directory hierarchy for this repo making sure it includes logical locations for the following components:
* spec (and spec generation tools)
* headers
* loader
* utility libraries (e.g. command buffer software implementation)
* test suite
* adapters

2. Actually restructure the repo.

**Comment by pbalcer** [comment]
Here's my proposal based on earlier one from @FranklandJack:
```
.
├── utils
│   ├── ci (runnners code)
│   ├── docker (docker image recipes + associated scripts)
│   └── ... (other random bits every project has (extra cmake scripts, *.pc files etc))
├── source
│   ├── adapters
│   │   ├── cuda
│   │   ├── hip
│   │   ├── null implementation
│   │   ├── level zero
│   │   └── opencl
│   ├── loader (current adapter is split between lib and loader directories, but I think we can just merge that) 
│   └── common 
├── include (header files + python bindings)
├── scripts 
│   ├── spec
│   ├── assets
│   └── templates
│       ├── include
│       ├── adapter
│       └── loader
├── examples 
└── test
     ├── common (any "framework" code or shared test utilities, e.g., mocks)
     ├── loader (loader-related unit tests)
     └── conformance
```

The thing we are implicitly changing with this is the naming of implementations - from driver to adapter. To be consistent, we should also rename 'ddi' (and other 'driver' derived terms) files and identifier names across the entire repo.

**Comment by kbenzie** [comment]
This looks good. Moving the `scripts/spec` to the top level would be the only tweak I'd suggest but I think that would also require fixing up the scripts so can probably be a separate issue.

I feel like we should be able make these changes incrementally without needing to block any particular move or integration.

**Comment by pbalcer** [comment]
I had it that way originally, but wasn't sure. I was thinking of doing a three-way split: spec, docs generation and code generation - but, as you say, that would require at least some changes to the existing scripts, so I'd prefer to avoid that.

We will create a PR that adds the loader, so we will do the first pass on the restructuring. But initially just around the source directory and cmakes, so that we don't run into conflicts with every single PR. After that we can make changes as we add the missing pieces like tests and a more comprehensive CI system.

**Comment by kbenzie** [comment]
In #79 I've updated the CMake to support the install target and FetchContent. It does touch the `source` directory so making you aware.

**Comment by kbenzie** [comment]
I believe we've actioned all of these changes.
