### ISSUE TITLE
Define and document a release process

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#806]
After [v0.7](https://github.com/oneapi-src/unified-runtime/releases/tag/v0.7) was tagged an issue was found which required a hotfix #800 and a subsequent patch version [v0.7.1](https://github.com/oneapi-src/unified-runtime/releases/tag/v0.7.1). That in turn required an change in https://github.com/intel/llvm/pull/10814. With the aim of shortening this process, here is a proposal:

Introduce release branches e.g., `v0.7`/`v0.7.x` or similar, which is will always contain the latest patch tag e.g., `v0.7.1`/`v0.7.2` etc. This could help with two things:

* Reduce the overhead of getting a hotfix into [intel/llvm](https://github.com/intel/llvm) or another upstream project by using the release branch rather than a specific tag.
* Allow releases to be hotfixed separately from the main branch, giving finer grain control over what actually makes up a patch release.

This issue is to prompt discussion about this proposed process, suggest improvements, or point out pitfalls.

The outcome of this issue should be documentation describing the release process and potentially introduce any automation to enable that process.

**Comment by jsji** [comment]
> Introduce release branches e.g., v0.7/v0.7.x or similar, which is will always contain the latest patch tag e.g., v0.7.1/v0.7.2 etc.

I think we need to define the criteria for increasing the tag number. If we increase the number whenever there is new commit, then we will still need a change in intel/llvm. eg: from v0.7 to v0.7.1.

**Comment by kbenzie** [comment]
> If we increase the number whenever there is new commit, then we will still need a change in intel/llvm. eg: from v0.7 to v0.7.1.

The idea here would be to have intel/llvm's FetchContent for the Unified Runtime repo point at the branch name not the specific tag. So then we could add a patch to the release branch without needing to update intel/llvm's FetchContent, tangentially we would also create a new tag with the patch version incremented.

We would absolutely need to define criteria for when this can/should happen, and be cautious about when its allowed. I think instances like the one which triggered the v0.7.1 patch is a good example, where an upstream caught a build failure.

**Comment by alycm** [comment]
The obvious pitfall of this is that a single commit ID of intel/llvm is no longer completely describing a checkout.  A commit in intel/llvm may be broken today but work tomorrow because Unified Runtime release branch changed (or vice-versa).

Hinders reproducibility and traceability.

**Comment by pbalcer** [comment]
I've used a similar branching approach in other projects, and it worked well. One thing that needs deciding is where fixes first land. The release branches, with fixes `git merge`'ed back to main, or to the main branch directly, with fixes being `git cherry-pick`'ed to release branches. I have no strong opinion either way. The `git merge` to main approach might be slightly more straightforward.

I'm also not sure about targeting a release branch instead of a specific tag. While it might seem as if this is no different than just using a newer shared library from the OS, which is a common practice, the coupling between the projects here is tighter. I would be most worried about accidentally breaking intel/llvm build with an innocent-looking change (like the one that prompted this discussion).

**Comment by kbenzie** [comment]
Conclusion from WG call is to move forwards with the proposal to create release branches and patch tags, starting with switching the CMake project version on the main branch to v0.8.

We will not *recommend* using the release branches downstream projects for the reasons detailed above.

**Comment by kbenzie** [comment]
I've created the [v0.7.x](https://github.com/oneapi-src/unified-runtime/tree/v0.7.x) branch which currently points to the [v0.7.1](https://github.com/oneapi-src/unified-runtime/releases/tag/v0.7.1) tag.
