### ISSUE TITLE
Prepare tracing layer to replace PI tracing capabilities

### ISSUE THREAD

**Issue by aarongreig** [oneapi-src/unified-runtime#821]
Replacing PI with UR will necessitate implementing [SYCL_PI_TRACE](https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#sycl_pi_trace-options) with the UR tracing layer. To do that we'll want the UR layer to match the capabilities of the PI tracing implementation 1:1. I've noticed a couple of disparities, there may be more:
- [x] #865
PI tracing seems to be able to report code location stuff https://github.com/intel/llvm/blob/sycl/sycl/source/detail/pi.cpp#L155 (line number, file etc)
- [x] #866
The PI tracing env var lets you choose from multiple levels of tracing. It's not like a particularly nuanced or granular thing but we want the env var to keep working the exact same way after the port so we'd better replicate something like it.

**Comment by pbalcer** [comment]
From what I can tell, `SYCL_PI_TRACE` seems to refer to what we are calling logging in UR - https://oneapi-src.github.io/unified-runtime/core/INTRO.html#logging. This functionality isn't being used uniformly across the entire codebase yet, but once it is, it will be more granular than the SYCL's setting.

We currently do *not* log, or have an option to log, all calls like PI does here: https://github.com/intel/llvm/blob/sycl/sycl/source/detail/plugin.hpp#L197. However, this can be accomplished with `urtrace`. Is that be sufficient?

I thought about adding code location to tracing, but ultimately at UR layer we don't have sufficient data to efficiently provide this information. The way it works in SYCL is by having information in TLS about where the top-level SYCL function was called, https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/detail/common.hpp#L100. The best we could do is use backtrace (https://github.com/oneapi-src/unified-runtime/blob/main/source/loader/layers/validation/backtrace.hpp) infrastructure we have for the validation layer. This would be a performance hit and might be unreliable. If we do must have this information, the only other idea I have is to require the user to provide us this information through a callback set through some new UR API.

**Comment by aarongreig** [comment]
We definitely do want to support code location the same way it's currently done, maybe we could make the layer enabling API extensible to allow a callback to be provided that lets the sycl runtime provide the location info from its `tls_code_loc_t`. It looks like the way it's currently accessed by the [XPTI stuff in PI](https://github.com/intel/llvm/blob/sycl/sycl/source/detail/pi.cpp#L155) is via a [global variable](https://github.com/intel/llvm/blob/sycl/sycl/source/detail/common.cpp#L55) that gets updated whenever a new `code_loc_t` is passed in. Sycl could provide a callback that accesses that variable and translates it into a ur equivalent struct.

The logging UR provides is for sure more feature rich in terms of options, but I think we should aim to keep the sycl user experience the same - i.e. one env var is enough (if you've built the sycl runtime + compiler with the right flags) to get API logs dumped into stdout when you run a sycl app. Maybe we could kind of emulate that by using putenv to set up the environment the same way urtrace does prior to initializing the UR runtime depending on the SYCL_PI_TRACE level? I'm not sure how sycl avoids having to have the `XPTI_FRAMEWORK_DISPATCHER` and `XPTI_SUBSCRIBERS` variables set for this to work

**Comment by pbalcer** [comment]
> Sycl could provide a callback that accesses that variable and translates it into a ur equivalent struct.

Yea, I'm not the biggest fan but I don't see a different approach either...

> I'm not sure how sycl avoids having to have the `XPTI_FRAMEWORK_DISPATCHER` and `XPTI_SUBSCRIBERS` variables set for this to work

That's the confusing part. `SYCL_PI_TRACE` doesn't control function tracing through XPTI, it controls log verbosity. The function logging that this can enable is done separately from the XPTI integration. So, in effect, to do the same thing, we could just add `info("{}", function)` inside the logger on every entry point, which would then allow users to set `UR_LOG_LOADER=info` to get the same information (to stderr, imho libraries should never output logs to stdout when not explicitly specified to do so) using just a single variable.
My opinion is that, if we ship `urtrace` alongside UR (installed in `/usr/bin`), using it will be as simple as `SYCL_PI_TRACE` and would provide more functionality. And we don't have to duplicate this functionality to provide a different interface.

**Comment by pbalcer** [comment]
Both features are now implemented, closing this issue.
