### ISSUE TITLE
Support sycl_ext_oneapi_memcpy2d extension

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#83]
https://github.com/intel/llvm/pull/7370 introduces support for the `sycl_ext_oneapi_memcpy2d` extension by adding 3 entry points to PI: `piextUSMEnqueueFill2D`, `piextUSMEnqueueMemset2D`, and `piextUSMEnqueueMemcpy2D`, along with supporting enumerations.

Add support to the unified runtime spec, the relevant changes for the spec are in the `sycl/include/sycl/detail/pi.h` header.

**Comment by steffenlarsen** [comment]
The enumerations added by the PR allows the backends to report whether they "natively" support the 2D USM operations, allowing the runtime to make fallback implementations of these if not. Does the unified runtime have a better mechanism for that than a context-level info query? If not, would there be a benefit to designing a more general way of determining if certain APIs are supported by a given backend?

**Comment by kbenzie** [comment]
As things stand UR is still catching up with PI in terms of functionality. We don't have a different mechanism for this kind of query at the moment, its an interesting idea.

Are the queries context-level because its only native if all devices in the context have support?

**Comment by steffenlarsen** [comment]
> Are the queries context-level because its only native if all devices in the context have support?

Context-level seemed like the best option for this as USM allocations are done at the same level, but I do not know of any existing backends that would answer the queries differently depending on the context/device(s), so it could as easily have been at platform-level.

Another option could have been a new return value (e.g. `PI_ERROR_UNSUPPORTED`) that the given API would return if it does not support the call, e.g. based on the arguments passed. That way it would have the freedom to always deny the call or do it based on one of the arguments, for example the context. That would also be somewhat simple to generalize for other APIs, but I do not know how well that plays into the UR design.
