### ISSUE TITLE
`urPlatformGet` & `urDeviceGet` should return valid error code.

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#85]
`urPlatformGet` currently says that "If phPlatforms is not NULL, then NumEntries but be greater than zero.", However we do not specify what should be returned in this case.

We should specify that `urPlatformGet` and `urDeviceGet` will return `UR_RESULT_ERROR_INVALID_SIZE` or something similar.

**Comment by veselypeta** [comment]
I'm not sure. This check in implemented in PI here https://github.com/intel/llvm/blob/sycl/sycl/plugins/level_zero/pi_level_zero.cpp#L2527. It also aligns with OpenCL https://registry.khronos.org/OpenCL/sdk/1.0/docs/man/xhtml/clGetDeviceIDs.html. However, if you believe that this can be done at the loader level then that seems fine with me. I don't know enough about the loader to comment.

**Comment by kbenzie** [comment]
I think, in the short term at least, there's value to adding these.

Once we have a validation layer we can reconsider where those types of checks should reside.
