### ISSUE TITLE
[CTS] Add testing for memory migration across devices in same context

### ISSUE THREAD

**Issue by hdelan** [oneapi-src/unified-runtime#862]
The CTS should add some testing to check that `ur_mem_handle_t_`s will automatically migrate memory from device to device within the same context.

Something like:

```
urEnqueueMemBufferWrite(// on Q1 in ctx
urEnqueueMemBufferRead(// on Q2 in ctx
// Wait and check that memory was migrated across queues
```
But with other entry points as well like kernel launches etc. Also for Image entry points.

**Comment by jandres742** [comment]
> The CTS should add some testing to check that ur_mem_handle_t_s will automatically migrate memory from device to device within the same context.

why are we adding that to a CTS? is that specified in the spec as mandatory behavior? Migrating memory between two devices could be implementation specific. For instance, an adapter may choose not to migrate if the underlying implementation offers faster performance for peer-to-peer access, rather than migration.

**Comment by hdelan** [comment]
My original comment is maybe poorly phrased. What the UR CTS ought to test for is whether memory in a UR buffer/image is available for multiple devices in a `ur_context_handle_t`. The method by which this should work is an implementation detail, and may rely on memory migration or by some other means such as P2P access. Nevertheless we should have some test which does something like:
```
// Using multi device ctx associated with queues {Q1, Q2}
urMemBufferCreate // Create buf
urEnqueueMemBufferWrite // Say on Q1
urEnqueueKernelLaunch // Write into buf on Q2
urEnqueueMemBufferRead // Read from buf on Q1 say. Make sure that the kernel on Q2 has had an effect on buffer.
```

**Comment by jandres742** [comment]
> My original comment is maybe poorly phrased. What the UR CTS ought to test for is whether memory in a UR buffer/image is available for multiple devices in a `ur_context_handle_t`. The method by which this should work is an implementation detail, and may rely on memory migration or by some other means such as P2P access. Nevertheless we should have some test which does something like:
> 
> ```
> // Using multi device ctx associated with queues {Q1, Q2}
> urMemBufferCreate // Create buf
> urEnqueueMemBufferWrite // Say on Q1
> urEnqueueKernelLaunch // Modify contents of buf on Q2
> urEnqueueMemBufferRead // Read from buf on Q1 say. Make sure that the kernel on Q2 has had an effect on buffer.
> ```

ah, thanks for the explanation @hdelan .
