### ISSUE TITLE
Introduce a clGetDeviceAndHostTimer analogue

### ISSUE THREAD

**Issue by kbenzie** [oneapi-src/unified-runtime#88]
https://github.com/intel/llvm/pull/7526 introduces the ability to query the device timestamp, this is an analogue of [clGetDeviceAndHostTimer](https://man.opencl.org/clGetDeviceAndHostTimer.html). We should also introduce this into the UR spec.

**Comment by veselypeta** [comment]
We should make `pHostTimer` & `pDeviceTimer` optional parameters so that `urDeviceGetGlobalTimestamps` can be used as an anologue of both `clGetDeviceAndHostTimer` and `clGetHostTimer`

**Comment by kbenzie** [comment]
Is this to match the behaviour in https://github.com/intel/llvm/pull/7526 ? Does the OpenCL analogue also make these optional?

**Comment by veselypeta** [comment]
They are required arguments in OpenCL, but the OpenCL plugin in PI does the following:

```cpp
  if (DeviceTime) {
    uint64_t dummy;
    clGetDeviceAndHostTimer(deviceID, DeviceTime,
                            HostTime == nullptr ? &dummy : HostTime);

  } else if (HostTime) {
    clGetHostTimer(deviceID, HostTime);
  }
```

**Comment by kbenzie** [comment]
Okay, so its to match the PI behaviour 👍
