### ISSUE TITLE
urModuleCreate and the void **pfnNotify parameter

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#9]
[`urModuleCreate`](https://github.com/oneapi-src/unified-runtime/blob/main/scripts/core/module.yml#L13)is declared as:
```
UR_APIEXPORT ur_result_t UR_APICALL urModuleCreate(ur_context_handle_t hContext, const void *pIL, uint32_t length, const char *pOptions, void **pfnNotify, void *pUserData, ur_module_handle_t *phModule)
```

It accepts a [`pfnNotify`](https://github.com/oneapi-src/unified-runtime/blob/main/scripts/core/module.yml#L36) argument that is supposed to be called when program compilation is complete, this is confusing for two reasons:

1. `urModuleCreate` doesn't have to do any compilation (it seems to just be an in memory representation of a SPIR-V string program, although maybe this is a misunderstanding), this may be handled further down the pipeline when you create the program, so why pass a callback here? In OpenCL [`clBuildProgram`](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clBuildProgram) takes a callback to be called when the program is built. `clBuildProgram` takes a `cl_program` object that has already been created via [`clCreateProgramWith(Source|IL|Binary)`](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_creating_program_objects). The `clCreateProgramWith.*` APIs do not take a callback, if these are the analogous entry points then should `urModuleCreate` take a callback?
2.  The type of `pfnNotify` is `void **`, which is not a function pointer. This is probably a typo and should be `void (*pfnNotify)` or `void * (*pfnNotify)` although the latter is unlikely since callbacks don't often return values, so the second `*` may also be a typo.

**Comment by veselypeta** [comment]
It appears that this parameter is part of PI to match `clBuildProgram`.
All calls from the SYCL runtime do not use this parameter: probably due to the fact that every other plugin has an `assert()` check to ensure this parameter is `nullptr`. 
It probably makes sense to remove.

**Comment by kbenzie** [comment]
#250 proposes to remove the module object.
