### ISSUE TITLE
Consider whether we should require adapters to bounds check USM operations

### ISSUE THREAD

**Issue by aarongreig** [oneapi-src/unified-runtime#926]
We currently mandate [bounds checks](https://github.com/oneapi-src/unified-runtime/blob/main/scripts/core/enqueue.yml#L1077) on our EnqueueUSM* type operations. None of the APIs we currently have adapters for have bounds checking on their equivalent operations: [OpenCL](https://registry.khronos.org/OpenCL/extensions/intel/cl_intel_unified_shared_memory.html#_filling_and_copying_unified_shared_memory), [Level Zero](https://spec.oneapi.io/level-zero/latest/core/api.html?highlight=kernelsetargumentvalue#zecommandlistappendmemorycopy), [Cuda](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1g5f26aaf5582ade791e5688727a178d78) (doesn't explicitly define conditions for each return code but lack of a distinct INVALID_SIZE type code would mean we have to do our own check to return the appropriate error even if cuda does do its own bounds checking). Since this is something we can't relegate to the validation layer implementing these entry points to spec means adding small but measurable, and unavoidable, additional overhead to these operations. The fact that most of the adapters, if not all of them, don't have these checks implemented currently suggests they aren't being missed, so we should consider removing them from the spec.

**Comment by fabiomestre** [comment]
Another similar issue would checking if events inside a wait list are null. This would also require either adding the check in the adapter or modifying the validation layers to iterate through the list of events. 

It currently fails in these tests:

* urEnqueueDeviceGetGlobalVariableReadTest:InvalidEventWaitInvalidEvent
* urEnqueueDeviceGetGlobalVariableWriteTest:InvalidEventWaitInvalidEvent
