### ISSUE TITLE
[UR][L0] Add support for multi-device kernel compilation

### ISSUE THREAD

**Issue by jandres742** [oneapi-src/unified-runtime#942]
PI interfaces accept a list of devices for ProgramBuild and alike. So first, we need to add the support to accept also a list of devices in the UR interfaces, and then we need to add the support in L0 adapter.

- [ ] Add the support for urProgramBuildExp interfaces and alike to accept a list of devices.
- [ ] Add support in L0 adapter for when more than 1 device is passed to those interfaces.

**Comment by jandres742** [comment]
@nrspruit to work on this.

**Comment by kbenzie** [comment]
I think this is done, please reopen if that's incorrect.
