### ISSUE TITLE
Reconsider urContextCreate Signature

### ISSUE THREAD

**Issue by FranklandJack** [oneapi-src/unified-runtime#97]
# Issue

The `urContextCreate` and `piContextCreate` entry points have different semantics.

`piContextCreate` has the following signature:
```
__SYCL_EXPORT pi_result piContextCreate(
    const pi_context_properties *properties, pi_uint32 num_devices,
    const pi_device *devices,
    void (*pfn_notify)(const char *errinfo, const void *private_info, size_t cb,
                       void *user_data),
    void *user_data, pi_context *ret_context);
```
`urContextCreate` has the following signature:
```
UR_APIEXPORT ur_result_t UR_APICALL
urContextCreate(
    uint32_t DeviceCount,                           ///< [in] the number of devices given in phDevices
    ur_device_handle_t* phDevices,                  ///< [in][range(0, DeviceCount)] array of handle of devices.
    ur_context_handle_t* phContext                  ///< [out] pointer to handle of context object created
    );
```

From the above we can note the following differences:
1. `piContextCreate` accepts a `properties` argument that is missing in `urContextCreate`.
2. `piContextCreate` accepts a `pfn_notify` callback and `user_data` that is passed to the callback. These arguments are missing in `urContextCreate`.

From the [usage of `piContextCreate`](https://github.com/intel/llvm/blob/5b13d5b6d364917c8ef3a7b51ffd01c8be580095/sycl/source/detail/context_impl.cpp#L58) in the DPC++ runtime we can see that `piContextCreate` is passed a properties argument so difference 1. is invalid. The callback arguments are null, so difference 2. is valid.

# Task

Add the `properties` argument to the `urContextCreate` entry point.

**Comment by FranklandJack** [comment]
The hip adapter only seems to handle [`__SYCL_PI_CONTEXT_PROPERTIES_HIP_PRIMARY`](https://github.com/intel/llvm/blob/c4932957929f94afe7f87bee009eea5e2b5cd6bf/sycl/plugins/hip/pi_hip.cpp#L1946) as a property ([as does CUDA](https://github.com/intel/llvm/blob/c4932957929f94afe7f87bee009eea5e2b5cd6bf/sycl/plugins/cuda/pi_cuda.cpp#L2086)). L0 [doesn't do anything with properties](https://github.com/intel/llvm/blob/179ffa16a929350c86a233ebfcaadc4be2e7be5f/sycl/plugins/level_zero/pi_level_zero.cpp#L3556) so this appears to be an OpenCL specific feature.

**Comment by kbenzie** [comment]
Recent changes to the CUDA plugin have made `__SYCL_PI_CONTEXT_PROPERTIES_CUDA_PRIMARY` no longer necessary, however the inverse of this option will likely be necessary moving forwards.
